/* Calibration is descriptive analysis only; it never promotes correlation to causation. */
window.MinshengCalibrationEngine=(()=>{
 const config=()=>window.MinshengCalibrationSeed.config;
 function run(spec,records,methodologyEvents=[]){const sourceId=spec.sourceIndicatorIds?.[0],targetId=spec.targetIndicatorId;if(!sourceId||!targetId)return {status:'DATA_INSUFFICIENT',reason:'SOURCE_AND_TARGET_REQUIRED'};const source=window.MinshengSeriesBuilder.build(records,sourceId,{frequency:spec.frequency||'monthly',transformation:spec.transformation?.source||'LEVEL',analysisCutoffDate:spec.analysisCutoffDate||config().analysisCutoffDate}),target=window.MinshengSeriesBuilder.build(records,targetId,{frequency:spec.frequency||'monthly',transformation:spec.transformation?.target||'LEVEL',analysisCutoffDate:spec.analysisCutoffDate||config().analysisCutoffDate}),sourceMeta=source.values[0],targetMeta=target.values[0],compatibility=sourceMeta&&targetMeta&&window.MinshengHistoricalBackfill?window.MinshengHistoricalBackfill.compatibility({frequency:source.frequency,transformation:sourceMeta.transformation||spec.transformation?.source,aggregation:sourceMeta.aggregation||'PERIOD'},{frequency:target.frequency,transformation:targetMeta.transformation||spec.transformation?.target,aggregation:targetMeta.aggregation||'PERIOD'}):'UNKNOWN';
  const pair=sourceMeta&&targetMeta&&window.MinshengPairReadiness?window.MinshengPairReadiness.check({frequency:source.frequency,transformation:sourceMeta.transformation||spec.transformation?.source,aggregation:sourceMeta.aggregation||'PERIOD',periodKind:sourceMeta.periodKind},{frequency:target.frequency,transformation:targetMeta.transformation||spec.transformation?.target,aggregation:targetMeta.aggregation||'PERIOD',periodKind:targetMeta.periodKind},{overrideReason:spec.pairOverrideReason||null}):null;if(pair?.status==='MISMATCH')return {status:'DATA_INSUFFICIENT',reason:pair.reason,pairReadiness:pair,sourceSeries:source,targetSeries:target};
  if(compatibility==='MISMATCH'||(compatibility==='PARTIAL_MATCH'&&!spec.allowPartialTransformation))return {status:'DATA_INSUFFICIENT',reason:compatibility==='PARTIAL_MATCH'?'TRANSFORMATION_PARTIAL_MATCH_REQUIRES_OVERRIDE':'TRANSFORMATION_MISMATCH',compatibility,sourceSeries:source,targetSeries:target};
  if(!source.values.length||!target.values.length)return {status:'DATA_INSUFFICIENT',reason:!source.values.length?'SOURCE_REAL_SERIES_MISSING':'TARGET_REAL_SERIES_MISSING',sourceSeries:source,targetSeries:target};
  const breakIndicators=new Set((methodologyEvents||[]).filter(e=>e.comparabilityImpact==='BREAK').map(e=>e.indicatorId));if((breakIndicators.has(sourceId)||breakIndicators.has(targetId))&&!spec.comparabilityOverride)return {status:'DATA_INSUFFICIENT',reason:'METHODOLOGY_BREAK_REQUIRES_SPLIT_OR_OVERRIDE',sourceSeries:source,targetSeries:target};
  const lags=window.MinshengLagExplorer.explore(source,target,spec.lags||[0,1,2,3,6,9,12]),eligible=lags.filter(x=>x.sampleSize>=config().MIN_CORRELATION_N&&Number.isFinite(x.pearson));if(!eligible.length)return {status:'DATA_INSUFFICIENT',reason:'INSUFFICIENT_SAMPLE',sourceSeries:source,targetSeries:target,lagResults:lags};
  const best=eligible.slice().sort((a,b)=>Math.abs(b.pearson)-Math.abs(a.pearson))[0],rows=window.MinshengSeriesBuilder.align(source,target,best.lag),regression=rows.length>=config().MIN_REGRESSION_N?window.MinshengRegressionEngine.ols(rows):{beta:null,intercept:null,rSquared:null,sampleSize:rows.length};return {status:'EXPLORATORY',sourceSeries:source,targetSeries:target,lagResults:lags,bestLag:best.lag,correlation:{pearson:best.pearson,spearman:best.spearman,sampleSize:best.sampleSize},regression,analysisCutoffDate:spec.analysisCutoffDate||config().analysisCutoffDate,disclaimer:'Correlation does not establish causality. 相关关系不代表因果关系。'};
 }
 function makeEvidence(result,calibration){return {id:`evidence_calibration_${Date.now()}`,title:`Calibration result: ${calibration.relationshipId}`,summary:result.disclaimer||result.reason,evidenceType:'ESTIMATE',stance:'NEUTRAL',confidence:null,importance:null,status:'REVIEW_REQUIRED',relatedIndicators:[...(calibration.sourceIndicatorIds||[]),calibration.targetIndicatorId].filter(Boolean),relatedResearch:calibration.researchIds||[],notes:'Calibration output requires manual research review; it is not a FACT.'};}
 return {run,makeEvidence};
})();
