window.MinshengPersistence = (() => {
  const key='minsheng-os-v03-local-research',storageVersion='0.19',clone=value=>JSON.parse(JSON.stringify(value));
  const legacyArrayKeys=['files','methodologyEvents','sourceDocuments','methodologies','documentSections','documentTables','records','auditLog','connectors','connectorRuns','rawPayloads','stagedRecords','sourceIndicatorMappings','methodologyHints','textLocators','policyThemes','policyStatements','policySignals','policyActions','reportComparisons','priorityShifts','policyDataLinks','executionGaps','institutionalResearch','forecasts','forecastRevisions','forecastResults','institutionRegistry','institutionalReports','assumptions','risks','forecastAssumptions','forecastRisks','institutionTrackRecords','institutionComparisons','calibrationRelationships','calibrations','calibrationResults','parameterVersions','scenarioParameters','scenariosV2','scenarioRunsV2','baselineSnapshots','regimes','criticalExposureItems','qualificationAssessments','calculationReadinessRecords','causalEdges','causalValidationRecords','downstreamStaleness','mortgageScenarioRuns','mortgageRateEvidence','distributionEvidence','mortgageContractEvidence','mortgageCohortRuns','bankCreditLossScenarioRuns','bankCreditLossScenarioMatrices','bankCreditLossScenarioAggregates','bankCreditLossScenarioReadiness','bankCreditLossScenarioGaps','forecastRegistrations','outcomeRecords','forecastOutcomeMatches','evaluationRuns','evaluationSummaries'];
  const legacyScalarDefaults={mortgageScenarioVersion:null,distributionScenarioVersion:null,bankCreditLossScenarioVersion:null,forecastOutcomeVersion:null,calibrationConfig:null,researchDataMode:'REAL + MOCK'};
  const compatibilityDefault=(target,name,value)=>{if(Object.hasOwn(target,name))return;Object.defineProperty(target,name,{value,writable:true,configurable:true,enumerable:false});};
  const migrate=(payload,version)=>{const next=clone(payload||{});legacyArrayKeys.forEach(name=>compatibilityDefault(next,name,[]));Object.entries(legacyScalarDefaults).forEach(([name,value])=>compatibilityDefault(next,name,value));(next.files||[]).forEach(item=>{item.storageType??='metadata_only';item.binaryStatus??=item.storageType==='indexeddb'?'unknown':'not_stored';});(next.sourceDocuments||[]).forEach(item=>{item.researchNotes??='';item.tags??=[];item.relatedResearchIds??=[];item.intelligenceType??=null;item.institutionId??=item.sourceId;item.reportingPeriod??=null;item.previousDocumentId??=null;item.nextDocumentId??=null;item.comparisonGroup??=null;item.analysisStatus??='RAW';item.immutable??=false;});(next.evidence||[]).forEach(item=>{if(item.locator&&item.locator.locatorNote===undefined)item.locator={documentId:item.sourceDocumentId||null,page:item.locator.page??null,sectionId:item.locator.sectionId??null,sectionTitle:item.locator.section??null,tableId:item.locator.tableId??null,tableTitle:item.locator.table??null,rowLabel:item.locator.row??null,columnLabel:item.locator.column??null,paragraph:item.locator.paragraph??null,quote:item.locator.quote??null,locatorNote:item.locator.note??null};});(next.scenarios||[]).forEach(item=>{item.legacyScenario??=true;});return next;};
  const load=base=>{try{const saved=JSON.parse(localStorage.getItem(key));if(!saved?.payload)return clone(base);const migrated=migrate(saved.payload,saved.version),merged={...clone(base),...migrated};['stateRegimeRegistry','currentStateSnapshots','stateFeatures','regimeEvidence','regimeCandidates','structuralBreakCandidates','regimeVersions','sectorBalanceSheets','sectorSnapshots','sectorExposures','sectorDataGaps','debtServiceMetrics','lossAllocationRuns','lossAllocationLinks','balanceSheetRepairAssessments','criticalExposureItems','qualificationAssessments','calculationReadinessRecords','causalEdges','causalValidationRecords','downstreamStaleness','mortgageScenarioRuns','mortgageRateEvidence','bankCreditLossScenarioRuns','bankCreditLossScenarioMatrices','bankCreditLossScenarioAggregates','bankCreditLossScenarioReadiness','bankCreditLossScenarioGaps','forecastRegistrations','outcomeRecords','forecastOutcomeMatches','evaluationRuns','evaluationSummaries'].forEach(name=>merged[name]??=[]);const mergeOfficial=(collection,predicate)=>{merged[collection]??=[];(base[collection]||[]).filter(predicate).forEach(item=>{const existing=merged[collection].find(candidate=>candidate.id===item.id);if(!existing)merged[collection].push(clone(item));else Object.assign(existing,clone(item));});};mergeOfficial('records',item=>item.status==='REAL'&&['nbs','pboc'].includes(item.sourceId));mergeOfficial('sourceDocuments',item=>['REAL','REAL_SOURCE'].includes(item.status)&&['nbs','pboc'].includes(item.sourceId));mergeOfficial('rawPayloads',item=>['nbs','pboc'].includes(item.sourceId));merged.seriesRegistry??=[];merged.historicalImportBatches??=[];merged.historicalStaging??=[];return merged}catch{return clone(base)}};
  const save=payload=>localStorage.setItem(key,JSON.stringify({version:storageVersion,savedAt:new Date().toISOString(),payload})),clear=()=>localStorage.removeItem(key);
  return {key,storageVersion,clone,load,save,clear,migrate};
})();
