/* REAL-only comparable series builder. */
window.MinshengSeriesBuilder=(()=>{
 const periodKey=value=>String(value||'').match(/^\d{4}-(?:0[1-9]|1[0-2])/)?.[0]||null;
 function build(records,indicatorId,{transformation='LEVEL',frequency='monthly',analysisCutoffDate=null}={}){
  const rows=(records||[]).filter(r=>r.status==='REAL'&&!r.deleted&&r.indicatorId===indicatorId&&r.frequency===frequency&&(!analysisCutoffDate||String(r.period)<=analysisCutoffDate)).map(r=>({period:periodKey(r.period),value:Number(r.convertedValue??r.value),recordId:r.id,seriesId:r.seriesId,sourceId:r.sourceId,sourceDocumentId:r.sourceDocumentId,revision:r.revision||0,qualityFlags:r.qualityFlags||[],observationType:r.observationType,transformation:r.transformation,aggregation:r.aggregation,periodKind:r.periodKind||null,methodologyBreak:r.comparabilityImpact==='BREAK'})).filter(r=>r.period&&Number.isFinite(r.value)).sort((a,b)=>a.period.localeCompare(b.period));
  const values=rows.map((row,index)=>{let value=row.value,alreadyRate=/_yoy$/i.test(indicatorId)||row.observationType==='growth_rate'||String(row.transformation).toLowerCase()==='yoy';if(transformation==='DIFF'&&index)value=row.value-rows[index-1].value;else if(transformation==='LOG'&&row.value>0)value=Math.log(row.value);else if(transformation==='LOG_DIFF'&&index&&row.value>0&&rows[index-1].value>0)value=Math.log(row.value)-Math.log(rows[index-1].value);else if(transformation==='YOY'&&!alreadyRate){const prior=rows[index-12];value=prior&&prior.value!==0?(row.value/prior.value-1)*100:null;}return {...row,value};}).filter(r=>Number.isFinite(r.value));
  return {indicatorId,frequency,transformation,seriesType:'REAL',values,recordIds:values.map(x=>x.recordId),periods:values.map(x=>x.period),sourceIds:[...new Set(values.map(x=>x.sourceId))],methodologyBreaks:values.filter(x=>x.methodologyBreak).map(x=>x.period),recordRevisionIds:values.map(x=>`${x.recordId}:r${x.revision}`),missingCount:rows.length-values.length};
 }
 function align(source,target,lag=0){const targets=new Map(target.values.map(row=>[row.period,row]));const shift=(period,count)=>{const [year,month]=period.split('-').map(Number),d=new Date(Date.UTC(year,month-1+count,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;};return source.values.map(row=>({source:row,target:targets.get(shift(row.period,lag))})).filter(x=>x.target).map(x=>({x:x.source.value,y:x.target.value,sourceRecordId:x.source.recordId,targetRecordId:x.target.recordId,period:x.target.period}));}
 return {build,align};
})();
