/* 民生OS v0.2: UI is rendered from the mock research data files in /data. */
const baseData = {
  sources: window.MinshengSources || [], indicators: window.MinshengIndicators || [], officialArtifactManifest:window.MinshengOfficialWave1Seed?.inventoryMeta||[], officialAcquisitionRuns:[], officialStagedCandidates:[], officialObservationReviews:[], officialLiveReports:[], officialReleases:window.MinshengOfficialWave2Seed?.releases||[], officialSourceRoutes:window.MinshengOfficialWave2Seed?.routes||[], officialDerivedRecords:window.MinshengOfficialWave2Seed?.derivedRecords||[], officialRevisionEvents:[], mortgageScenarioRuns:[], mortgageRateEvidence:[], mortgageScenarioVersion:null, distributionEvidence:[], mortgageContractEvidence:[], mortgageCohortRuns:[], distributionScenarioVersion:null, developerCashflowRuns:[], realEstateFundingEvidence:[], developerCashflowDerivedRecords:[], developerCashflowScenarioVersion:null, internationalProviders:[], internationalConcepts:[], internationalCoverageGaps:[], internationalObservationRecords:[], internationalComparisons:[], internationalComparisonAssessments:[], internationalDerivedTransformations:[], internationalStatisticsVersion:null,bankDisclosureRecords:[],bankDisclosureAssessments:[],bankSampleCoverage:[],bankDisclosureRuns:[],bankAssetQualityRecords:[],bankAssetQualityDerivedRecords:[],bankAssetQualityAssessments:[],bankAssetQualityCoverage:[],bankAssetQualityRuns:[],bankCreditLossScenarioRuns:[],bankCreditLossScenarioMatrices:[],bankCreditLossScenarioAggregates:[],bankCreditLossScenarioReadiness:[],bankCreditLossScenarioGaps:[],bankCreditLossScenarioVersion:null,crossSectorScenarioCases:[],crossSectorScenarioComparisons:[],crossSectorDependencyGraphs:[],crossSectorConsistencyAssessments:[],crossSectorScenarioVersion:null,
  intelligence: window.MinshengIntelligence || [], relationships: window.MinshengRelationships || [],
  scenarios: window.MinshengScenarios || [], scenariosV2:window.MinshengScenariosV2||[], regimes:window.MinshengRegimes||[], stateRegimeRegistry:window.MinshengStateRegimeRegistry||[], currentStateSnapshots:[], stateFeatures:[], regimeEvidence:window.MinshengRegimeEvidence||[], regimeCandidates:window.MinshengRegimeCandidates||[], structuralBreakCandidates:window.MinshengStructuralBreakCandidates||[], regimeVersions:window.MinshengRegimeVersions||[], sectorBalanceSheets:window.MinshengSectorBalanceSheets||[], sectorSnapshots:[], sectorExposures:window.MinshengSectorExposures||[], sectorDataGaps:window.MinshengSectorDataGaps||[], debtServiceMetrics:window.MinshengDebtServiceMetrics||[], lossAllocationRuns:window.MinshengLossAllocationRuns||[], lossAllocationLinks:window.MinshengLossAllocationLinks||[], balanceSheetRepairAssessments:window.MinshengBalanceSheetRepairAssessments||[], criticalExposureItems:window.MinshengCriticalExposureItems||[], qualificationAssessments:window.MinshengQualificationAssessments||[], calculationReadinessRecords:window.MinshengCalculationReadinessRecords||[], causalEdges:window.MinshengCausalEdges||[], causalValidationRecords:[], downstreamStaleness:window.MinshengDownstreamStaleness||[], causalStudyRecords:[],causalEstimateRecords:[],causalParameterCandidates:[],transferabilityAssessments:[],causalEdgeReviewProposals:[],causalEvidenceAuditLog:[],causalEvidenceVersion:null, scenarioParameters:window.MinshengScenarioParameters||[], parameterVersions:window.MinshengParameterVersions||[], scenarioRunsV2:window.MinshengScenarioRunsV2||[], baselineSnapshots:window.MinshengBaselineSnapshots||[], cities: window.MinshengCities || [], research: window.MinshengResearch || [], evidence: window.MinshengEvidence || [], inbox: window.MinshengEvidenceInbox || [], records:window.MinshengDataRecords||[], rawPayloads:window.MinshengRawPayloads||[], methodologies:window.MinshengMethodologies||[], methodologyEvents:window.MinshengMethodologyEvents||[], sourceDocuments:window.MinshengSourceDocuments||[], files:window.MinshengFiles||[], documentSections:window.MinshengDocumentSections||[], documentTables:window.MinshengDocumentTables||[], batches:window.MinshengImportBatches||[], policyStatements:window.MinshengPolicyStatements||[], policyActions:window.MinshengPolicyActions||[], priorityShifts:window.MinshengPriorityShifts||[], auditLog:[], canonicalOverrides:{}
};
const data = window.MinshengPersistence ? window.MinshengPersistence.load(baseData) : baseData;
/* v0.30: operations telemetry is read-only audit metadata, never an observation materialization path. */
const officialOpsSeed=window.MinshengOfficialDataOpsSeed||{};
[['officialOpsRegistry','registry'],['officialOpsRuns','runs'],['officialOpsArtifacts','artifacts'],['officialOpsCandidates','candidates'],['officialOpsSemanticDiffs','semanticDiffs'],['officialOpsApprovals','approvals'],['officialOpsSubmissions','submissions'],['officialOpsSourceHealth','sourceHealth'],['officialOpsRecoveryEvents','recoveryEvents']].forEach(([store,key])=>{data[store]??=[];(officialOpsSeed[key]||[]).forEach(item=>{if(!data[store].some(existing=>existing.id===item.id))data[store].push(JSON.parse(JSON.stringify(item)));});});
const officialWatchSeed=window.MinshengOfficialReleaseWatchSeed||{};
[['officialReleaseCalendars','calendars'],['officialWatchJobs','watchJobs'],['officialReviewQueue','reviewQueue'],['officialWatchLocks','locks'],['officialSchedulerStatus','scheduler'],['officialWatchRuns','runs']].forEach(([store,key])=>{data[store]??=[];(officialWatchSeed[key]||[]).forEach(item=>{if(!data[store].some(existing=>existing.id===item.id))data[store].push(JSON.parse(JSON.stringify(item)));});});
const briefingSeed=window.MinshengResearchBriefingSeed||{};
[['researchBriefings','briefings'],['briefingStatements','statements'],['briefingHistory','history']].forEach(([store,key])=>{data[store]??=[];(briefingSeed[key]||[]).forEach(item=>{if(!data[store].some(existing=>existing.id===item.id||existing.briefingId===item.briefingId))data[store].push(JSON.parse(JSON.stringify(item)));});});
/* v0.15: a persisted pre-Wave-2 browser state must still receive immutable official seed records. */
const mergeOfficialSeed=(collection,items)=>{data[collection]??=[];(items||[]).forEach(item=>{const existing=data[collection].find(row=>row.id===item.id);if(existing)Object.assign(existing,JSON.parse(JSON.stringify(item)));else data[collection].push(JSON.parse(JSON.stringify(item)));});};
const wave2Seed=window.MinshengOfficialWave2Seed||{};mergeOfficialSeed('indicators',(window.MinshengIndicators||[]).filter(item=>item.tags?.includes('v0.15')));mergeOfficialSeed('criticalExposureItems',wave2Seed.criticalItems);mergeOfficialSeed('records',wave2Seed.records);mergeOfficialSeed('sourceDocuments',wave2Seed.documents);mergeOfficialSeed('rawPayloads',wave2Seed.rawPayloads);mergeOfficialSeed('officialReleases',wave2Seed.releases);mergeOfficialSeed('officialSourceRoutes',wave2Seed.routes);mergeOfficialSeed('officialDerivedRecords',wave2Seed.derivedRecords);mergeOfficialSeed('officialLiveReports',[wave2Seed.liveReport]);
const mortgageSeed=window.MinshengMortgageScenarioSeed||{};mergeOfficialSeed('records',mortgageSeed.rateRecords);mergeOfficialSeed('sourceDocuments',mortgageSeed.documents);mergeOfficialSeed('rawPayloads',mortgageSeed.rawPayloads);mergeOfficialSeed('officialReleases',mortgageSeed.releases);mergeOfficialSeed('officialSourceRoutes',mortgageSeed.routes);mergeOfficialSeed('research',mortgageSeed.research);
const distributionSeed=window.MinshengDistributionCohortSeed||{};mergeOfficialSeed('records',distributionSeed.records);mergeOfficialSeed('sourceDocuments',[distributionSeed.document]);mergeOfficialSeed('rawPayloads',[distributionSeed.raw]);mergeOfficialSeed('officialReleases',[distributionSeed.release]);mergeOfficialSeed('officialSourceRoutes',[distributionSeed.route]);mergeOfficialSeed('distributionEvidence',distributionSeed.evidence);mergeOfficialSeed('mortgageContractEvidence',distributionSeed.contractEvidence);mergeOfficialSeed('research',distributionSeed.research);
const developerCashflowSeed=window.MinshengDeveloperCashflowSeed||{};mergeOfficialSeed('records',developerCashflowSeed.records);mergeOfficialSeed('sourceDocuments',[developerCashflowSeed.document]);mergeOfficialSeed('rawPayloads',[developerCashflowSeed.raw]);mergeOfficialSeed('officialReleases',[developerCashflowSeed.release]);mergeOfficialSeed('officialSourceRoutes',[developerCashflowSeed.route]);mergeOfficialSeed('developerCashflowDerivedRecords',developerCashflowSeed.derivedRecords);mergeOfficialSeed('research',developerCashflowSeed.research);
const internationalSeed=window.MinshengInternationalStatisticsSeed||{};mergeOfficialSeed('internationalProviders',internationalSeed.providers);mergeOfficialSeed('internationalConcepts',internationalSeed.concepts);mergeOfficialSeed('internationalCoverageGaps',internationalSeed.gaps);mergeOfficialSeed('internationalObservationRecords',internationalSeed.records);mergeOfficialSeed('internationalObservationRecords',internationalSeed.db);mergeOfficialSeed('internationalComparisons',internationalSeed.comparisons);
const comparisonPackSeed=window.MinshengInternationalComparisonPackSeed||{};mergeOfficialSeed('internationalProviders',comparisonPackSeed.providers);mergeOfficialSeed('internationalConcepts',comparisonPackSeed.concepts);mergeOfficialSeed('internationalCoverageGaps',comparisonPackSeed.gaps);mergeOfficialSeed('internationalObservationRecords',comparisonPackSeed.records);mergeOfficialSeed('internationalComparisonAssessments',comparisonPackSeed.assessments);mergeOfficialSeed('internationalDerivedTransformations',comparisonPackSeed.derived);
const bankExposureSeed=window.MinshengBankExposureSeed||{};mergeOfficialSeed('bankDisclosureRecords',bankExposureSeed.records);mergeOfficialSeed('bankDisclosureAssessments',bankExposureSeed.assessments);mergeOfficialSeed('bankSampleCoverage',bankExposureSeed.coverage);mergeOfficialSeed('bankDisclosureRuns',[bankExposureSeed.run]);
const bankAssetQualitySeed=window.MinshengBankAssetQualitySeed||{};mergeOfficialSeed('bankAssetQualityRecords',bankAssetQualitySeed.records);mergeOfficialSeed('bankAssetQualityDerivedRecords',bankAssetQualitySeed.derivedRecords);mergeOfficialSeed('bankAssetQualityAssessments',bankAssetQualitySeed.assessments);mergeOfficialSeed('bankAssetQualityCoverage',bankAssetQualitySeed.coverage);mergeOfficialSeed('bankAssetQualityRuns',[bankAssetQualitySeed.run]);
const bankCreditLossScenarioSeed=window.MinshengBankCreditLossScenarioSeed||{};mergeOfficialSeed('bankCreditLossScenarioReadiness',bankCreditLossScenarioSeed.readiness);mergeOfficialSeed('bankCreditLossScenarioGaps',bankCreditLossScenarioSeed.gaps);mergeOfficialSeed('research',bankCreditLossScenarioSeed.research);
const appState = { feedFilter: '全部', feedSort: 'time', scenarioId: 'baseline', evidenceFilter:'全部', evidenceTypeFilter:'全部', evidenceSourceFilter:'全部' };
const titleMap={overview:['态势总览','中国民生研究态势'],intelligence:['情报流','研究信息与证据队列'],causal:['因果与传导','经济传导图谱'],property:['房地产系统','房地产反馈网络'],cities:['城市制度','城市制度竞争力'],household:['居民部门','居民资产负债表'],evidence:['证据库','Evidence Engine'],intake:['数据接入','Data Intake & Provenance'],sources:['来源与血缘','Source Registry & Data Lineage'],library:['资料库','Source Document Intelligence'],methodologies:['统计口径','Methodology Intelligence'],research:['研究记忆','Evidence & Research Memory'],scenarios:['情景推演','Scenario Engine'],watchlist:['观察清单','研究观察清单']};
const byId = id => document.getElementById(id);
const sourceOf = id => data.sources.find(x => x.id === id) || { name: '未标注来源', type: 'unknown' };
const indicatorOf = id => data.indicators.find(x => x.id === id);
const fmtDate = value => value ? value.replaceAll('-', '.') : '—';
const qualityScore = q => Math.round(((q.completeness + q.freshness + q.reliability + q.comparability) / 4) * 100);
const qualityLabel = score => score >= 75 ? '高' : score >= 50 ? '中' : '低';
const evidenceClass = type => ({FACT:'green',ESTIMATE:'purple',INFERENCE:'amber',HYPOTHESIS:'purple',FORECAST:'amber',SCENARIO:'neutral',OPINION:'neutral'})[type] || 'neutral';
const badge = type => `<span class="metric-chip ${evidenceClass(type)}">${type}</span>`;
const demoFlag = status => status === 'demo' ? '<span class="demo-flag">DEMO DATA</span>' : '';

function showView(id){
  document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));
  byId(id)?.classList.add('active-view');
  document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===id));
  const [k,t]=titleMap[id]||titleMap.overview; byId('view-kicker').textContent=k; byId('view-title').textContent=t;
  window.scrollTo({top:0,behavior:'smooth'});
}

function renderIndicators() {
  const selected = ['household_deposit','household_consumption','second_hand_home_price'];
  const container = document.querySelector('.signal-row');
  if (!container) return;
  container.innerHTML = selected.map(id => {
    const item = indicatorOf(id), source = sourceOf(item.sourceId), score = qualityScore(item.dataQuality);
    const direction = item.direction === 'up' ? '↑' : item.direction === 'down' ? '↓' : '→';
    const movement = item.direction === 'up' ? 'upward' : item.direction === 'down' ? 'downward' : 'flat';
    return `<article class="signal-card data-card" data-indicator="${item.id}">
      <div class="signal-head"><span>${item.module}</span><button aria-label="查看指标">↗</button></div>
      <div class="metric">${item.value} <small>${item.unit}</small> ${demoFlag(item.status)}</div>
      <p class="change ${movement}">${direction} 对比上期：${item.previousValue} ${item.unit}</p>
      <div class="card-meta">${badge(item.evidenceType)} <span>${source.name}</span></div>
      <div class="card-footer"><span>${item.period} · 更新 ${fmtDate(item.updatedAt)}</span><span>质量 ${qualityLabel(score)} ${score}%</span></div>
    </article>`;
  }).join('');
  container.querySelectorAll('[data-indicator]').forEach(card => card.addEventListener('click', () => openIndicatorDetail(card.dataset.indicator)));
}

function renderResearchNotes() {
  const map = document.querySelector('.system-map');
  if (!map) return;
  document.querySelector('.research-notes')?.remove();
  map.insertAdjacentHTML('afterend', `<section class="panel research-notes"><div class="panel-title"><div><p class="eyebrow">当前重点研究问题</p><h2>等待证据回答，而非预设结论</h2></div><button class="text-btn" data-target="evidence">研究透明度 →</button></div><div class="notes-grid">${data.research.map(note => `<button class="research-note" data-note="${note.id}">${badge(note.status)}<b>${note.title}</b><span>置信度 ${Math.round(note.confidence*100)}% · 需 ${note.requiredData.length} 类数据</span></button>`).join('')}</div></section>`);
  map.parentElement.querySelector('[data-target="evidence"]').onclick = () => showView('evidence');
  map.parentElement.querySelectorAll('[data-note]').forEach(note => note.onclick = () => openResearchDetail(note.dataset.note));
}

function intelligenceItems() {
  const filter = appState.feedFilter;
  let items = data.intelligence.filter(item => filter === '全部' || item.tags.includes(filter) || item.relatedModules.includes(filter) || (filter === '官方' && sourceOf(item.sourceId).type === 'official_primary'));
  return items.sort((a,b) => appState.feedSort === 'importance' ? ({high:3,medium:2,low:1}[b.importance] - {high:3,medium:2,low:1}[a.importance]) : b.publishedAt.localeCompare(a.publishedAt));
}
function renderDashboardFeed() {
  const list = document.querySelector('.feed-list'); if (!list) return;
  list.innerHTML = intelligenceItems().slice(0,3).map(item => `<div class="feed-item"><span class="type ${sourceOf(item.sourceId).type === 'official_primary' ? 'official' : item.tags.includes('国际') ? 'multilateral' : 'market'}">${sourceOf(item.sourceId).name}</span><div><b>${item.title} ${badge(item.evidenceType)}</b><p>${item.summary}</p></div><time>${fmtDate(item.publishedAt)}</time></div>`).join('');
}
function renderIntelligenceFeed() {
  const section = byId('intelligence'); if (!section) return;
  const tools = section.querySelector('.table-tools');
  tools.innerHTML = `<div class="tabs feed-filters">${['全部','官方','央行','财政','房地产','居民','国际','政策','市场','社会认知'].map(f => `<button class="${appState.feedFilter===f?'selected':''}" data-filter="${f}">${f}</button>`).join('')}</div><div class="sort-control"><label>排序 <select id="feedSort"><option value="time">时间</option><option value="importance">重要度</option><option value="evidence">证据等级</option></select></label></div>`;
  tools.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{appState.feedFilter=button.dataset.filter;renderIntelligenceFeed();renderDashboardFeed()});
  const sort = byId('feedSort'); sort.value = appState.feedSort; sort.onchange = e => {appState.feedSort=e.target.value;renderIntelligenceFeed();renderDashboardFeed()};
  const body = section.querySelector('tbody');
  body.innerHTML = intelligenceItems().map(item => { const source=sourceOf(item.sourceId); return `<tr data-intel="${item.id}"><td><b>${item.title}</b><small>${item.summary}</small></td><td>${source.type}</td><td>${badge(item.evidenceType)}<small>置信度 ${Math.round(item.confidence*100)}%</small></td><td><span class="status ${item.importance === 'high' ? 'review' : 'ready'}">${item.importance === 'high' ? '优先研判' : '已入队列'}</span></td><td>${fmtDate(item.publishedAt)}</td></tr>` }).join('');
  body.querySelectorAll('[data-intel]').forEach(row => row.onclick=()=>openIntelligenceDetail(row.dataset.intel));
}

function renderCausalGraph() {
  const canvas=document.querySelector('.graph-canvas'), detail=document.querySelector('.edge-card'); if (!canvas || !detail) return;
  const relations=data.relationships, nodes=[...new Set(relations.flatMap(r=>[r.from,r.to]))].map(indicatorOf).filter(Boolean);
  const positions=['left:5%;top:14%','left:5%;bottom:15%','left:42%;top:41%','right:5%;top:18%','right:5%;bottom:14%','left:25%;top:5%','left:41%;bottom:5%'];
  canvas.innerHTML=`<svg viewBox="0 0 800 410" preserveAspectRatio="none"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#6e807c"/></marker></defs>${relations.map((r,i)=>`<path class="${r.evidenceType==='HYPOTHESIS'?'dashed':''}" data-rel="${r.id}" d="${['M145 105 C260 105,260 205,365 205','M145 305 C250 305,275 220,365 220','M460 205 C545 205,560 120,650 120','M460 215 C545 220,560 305,650 305'][i] || 'M460 215 C545 220,560 305,650 305'}" marker-end="url(#arrow)"/>`).join('')}</svg>${nodes.map((n,i)=>`<button class="g-node ${i===2?'focus':''}" style="${positions[i] || positions[3]}" data-node="${n.id}">${n.name}<small>${n.evidenceType} · ${n.period}</small></button>`).join('')}`;
  canvas.querySelectorAll('[data-node]').forEach(node=>node.onclick=()=>openIndicatorDetail(node.dataset.node));
  canvas.querySelectorAll('[data-rel]').forEach(path=>path.onclick=()=>openRelationshipDetail(path.dataset.rel));
  openRelationshipDetail(relations[0]?.id, true);
}
function openRelationshipDetail(relId, quiet=false) {
  const r=data.relationships.find(x=>x.id===relId), from=indicatorOf(r?.from), to=indicatorOf(r?.to), detail=document.querySelector('.edge-card'); if(!r||!detail)return;
  const strength=Math.round(r.strength*100), confidence=Math.round(r.confidence*100), supporting=r.supportingEvidence.length, opposing=r.contradictingEvidence.length;
  const evidenceLinks=[...r.supportingEvidence,...r.contradictingEvidence].filter(id=>data.evidence.some(e=>e.id===id));
  detail.innerHTML=`<p class="eyebrow">关系证据卡</p><h2>${from.name} → ${to.name}</h2>${badge(r.evidenceType)}<dl><dt>作用方向</dt><dd>${r.direction==='positive'?'正向':'负向'}</dd><dt>关系强度</dt><dd><div class="strength">${[1,2,3,4,5].map(n=>`<i class="${n>Math.ceil(r.strength*5)?'empty':''}"></i>`).join('')}</div> ${strength}%</dd><dt>研究置信度</dt><dd>${confidence}%</dd><dt>预计影响滞后</dt><dd>${r.lag.min}—${r.lag.max} 个月</dd></dl><hr><b>作用机制</b><p>${r.mechanism}</p><div class="evidence-count"><span>支持证据 ${supporting}</span><span>反对证据 ${opposing}</span></div><button class="secondary" data-target="evidence">查看相关证据</button>`;
  if (evidenceLinks.length) detail.insertAdjacentHTML('beforeend',`<div class="relation-evidence-links">${evidenceLinks.map(id=>`<button data-relation-evidence="${id}">打开证据：${data.evidence.find(e=>e.id===id).title}</button>`).join('')}</div>`);
  detail.querySelector('[data-target]').onclick=()=>{appState.evidenceFilter='全部';showView('evidence');renderEvidenceEngine();};
  detail.querySelectorAll('[data-relation-evidence]').forEach(button=>button.onclick=()=>openEvidenceDetail(button.dataset.relationEvidence));
  if (!quiet) detail.scrollIntoView({behavior:'smooth',block:'nearest'});
}

function cityScore(c) { return Math.round((100-c.policyExecutionFriction + 100-c.institutionalReplicationFriction + c.startupActivity + c.privateEconomyVitality + c.talentAttraction + c.governmentDigitalization + c.financingEnvironment + c.industrialEcosystem) / 8); }
function renderCityResearch() {
  const section=byId('cities'); if(!section)return;
  section.classList.remove('placeholder');
  const cities=[...data.cities].sort((a,b)=>cityScore(b)-cityScore(a));
  section.innerHTML=`<div class="view-intro"><p class="eyebrow">City institutional competitiveness</p><h1>城市制度研究</h1><p>PEF 与 IRF 均为研究模型演示值，不能视为官方营商环境排名。PEF 越低越好；IRF 越低越易复制成熟制度。</p></div><div class="panel city-table"><div class="demo-strip">DEMO MODEL · 非官方排名 · 所有评分待真实研究数据验证</div><table><thead><tr><th>城市</th><th>PEF ↓</th><th>IRF ↓</th><th>创业活跃度</th><th>民企活力</th><th>人才吸引</th><th>研究模型综合值</th><th>证据</th></tr></thead><tbody>${cities.map(c=>`<tr><td><b>${c.name}</b></td><td>${c.policyExecutionFriction}</td><td>${c.institutionalReplicationFriction}</td><td>${c.startupActivity}</td><td>${c.privateEconomyVitality}</td><td>${c.talentAttraction}</td><td><b>${cityScore(c)}</b></td><td>${badge(c.evidenceType)}</td></tr>`).join('')}</tbody></table></div>`;
}
function researchModuleCards(category, title, intro) {
  const indicators=data.indicators.filter(x=>x.category===category);
  return `<div class="view-intro"><p class="eyebrow">Research module</p><h1>${title}</h1><p>${intro}</p></div><div class="module-grid">${indicators.map(item=>{const source=sourceOf(item.sourceId);return `<button class="panel mini-indicator" data-indicator="${item.id}"><div><p class="eyebrow">${item.name}</p><b>${item.value}<small>${item.unit}</small></b></div><div>${demoFlag(item.status)}${badge(item.evidenceType)}</div><p>${source.name} · ${item.period}</p><small>数据质量 ${qualityLabel(qualityScore(item.dataQuality))} · 置信度 ${Math.round(item.confidence*100)}%</small></button>`}).join('')}</div>`;
}
function renderModules() {
  const property=byId('property'), household=byId('household');
  property.classList.remove('placeholder'); property.innerHTML=researchModuleCards('property','房地产系统','从价格、成交、库存、土地到按揭信贷，观察反馈关系；所有数值均为 MOCK。');
  household.classList.remove('placeholder'); household.innerHTML=researchModuleCards('household','居民部门','按资产负债表、收入预期与消费行为分层研究；样本调查不代表全国人口。');
  [property,household].forEach(section=>section.querySelectorAll('[data-indicator]').forEach(card=>card.onclick=()=>openIndicatorDetail(card.dataset.indicator)));
}
function renderScenario() {
  const section=byId('scenarios'); if(!section)return;
  const current=data.scenarios.find(x=>x.id===appState.scenarioId)||data.scenarios[0], result=runScenario(current);
  section.innerHTML=`<div class="view-intro"><p class="eyebrow">Rule-based scenario engine</p><h1>情景推演</h1><p>情景不是预测：仅在预设条件下，按有限因果关系传播变化。</p></div><div class="scenario-grid"><section class="panel scenario-selector"><p class="eyebrow">选择框架</p>${data.scenarios.map(s=>`<button class="scenario ${s.id===current.id?'active':''}" data-scenario="${s.id}"><span>${s.code}</span><b>${s.name}</b><small>${s.description}</small></button>`).join('')}</section><section class="panel scenario-result"><div class="demo-strip">DEMO SCENARIO · 不构成现实预测、投资或政策建议</div><p class="eyebrow">${current.code} · 条件性推演</p><h2>${current.name}</h2><div class="scenario-chain">${Object.entries(current.changes).map(([id,value])=>`<span>${indicatorOf(id)?.name || id} ${value>0?'+':''}${value}%</span>`).join('<i>→</i>')}</div><div class="impact-grid"><div><b>直接影响</b><p>${result.direct || '当前无直接冲击。'}</p></div><div><b>二阶影响</b><p>${result.second || '未发现可传播的关系。'}</p></div><div><b>三阶影响</b><p>${result.third || '需补充更多关系后计算。'}</p></div><div><b>预计滞后 / 置信度</b><p>${result.lag} · ${Math.round(result.confidence*100)}%</p></div></div><button class="primary" id="scenarioExplain">查看传播依据</button></section></div>`;
  section.querySelectorAll('[data-scenario]').forEach(button=>button.onclick=()=>{appState.scenarioId=button.dataset.scenario;renderScenario()});
  byId('scenarioExplain').onclick=()=>showView('causal');
}
function runScenario(scenario) {
  const direct=Object.entries(scenario.changes).map(([id,v])=>`${indicatorOf(id)?.name || id} ${v>0?'+':''}${v}%`).join('；');
  const affected=data.relationships.filter(r=>Object.keys(scenario.changes).includes(r.from));
  const second=affected.map(r=>`${indicatorOf(r.to)?.name}：${r.direction==='positive'?'同向':'反向'}变化（关系强度 ${Math.round(r.strength*100)}%）`).join('；');
  const third=affected.flatMap(first=>data.relationships.filter(r=>r.from===first.to)).map(r=>`${indicatorOf(r.to)?.name}：存在后续传导可能`).join('；');
  const maxLag=affected.reduce((max,r)=>Math.max(max,r.lag.max),0);
  const confidence=affected.length?affected.reduce((sum,r)=>sum+r.confidence,0)/affected.length*scenario.confidence:scenario.confidence;
  return {direct,second,third,lag:maxLag?`预计 ${maxLag} 个月内出现主要二阶影响`:'未设置传导滞后',confidence};
}
function renderEvidence() {
  const section=byId('evidence'); if(!section)return;
  section.classList.remove('placeholder');
  section.innerHTML=`<div class="view-intro"><p class="eyebrow">Evidence engine</p><h1>证据库与研究透明度</h1><p>结论 → 推理 → 数据 → 来源。不同证据状态不能互相替代。</p></div><div class="evidence-layout"><section class="panel"><div class="panel-title"><div><p class="eyebrow">来源目录</p><h2>${data.sources.length} 个预置来源</h2></div><span class="demo-flag">MOCK CATALOG</span></div><div class="source-list">${data.sources.map(s=>`<div><b>${s.name}</b><span>${s.type}</span><small>信任等级：${s.trustLevel}</small></div>`).join('')}</div></section><section class="panel transparency"><p class="eyebrow">Research Transparency</p><h2>研究辅助，不替代判断</h2><p>民生OS是一套研究辅助系统。系统中的内容可能包含事实、估算、推断、假设、预测、情景和观点，所有内容应根据证据等级区别理解。</p><p>任何模拟结果不构成投资、政策或经济决策建议。</p><div class="state-legend">${['FACT','ESTIMATE','INFERENCE','HYPOTHESIS','FORECAST','SCENARIO','OPINION'].map(badge).join('')}</div></section></div>`;
}
function saveLocalResearch() { window.MinshengPersistence?.save({research:data.research,evidence:data.evidence,inbox:data.inbox,indicators:data.indicators,records:data.records,rawPayloads:data.rawPayloads,batches:data.batches,auditLog:data.auditLog,canonicalOverrides:data.canonicalOverrides,sourceDocuments:data.sourceDocuments,files:data.files,methodologies:data.methodologies,methodologyEvents:data.methodologyEvents,documentSections:data.documentSections,documentTables:data.documentTables}); }
function statusText(status) { return ({OPEN:'开放研究',HYPOTHESIS:'研究假设',SUPPORTED:'支持中',WEAKENED:'反证增强',DISPUTED:'存在争议',REJECTED:'已否定',INCONCLUSIVE:'待补数据',ARCHIVED:'已归档'})[status] || status; }
function createV03Views() {
  const evidenceNav=document.querySelector('.nav-item[data-view="evidence"]');
  if (evidenceNav && !document.querySelector('.nav-item[data-view="research"]')) evidenceNav.insertAdjacentHTML('afterend','<button class="nav-item" data-view="research"><i>◈</i>研究记忆</button>');
  if (!byId('research')) byId('scenarios').insertAdjacentHTML('beforebegin','<section id="research" class="view"></section>');
}
function renderResearchWorkspace() {
  const section=byId('research'); if(!section)return;
  const statuses=['OPEN','HYPOTHESIS','SUPPORTED','DISPUTED','WEAKENED','REJECTED','INCONCLUSIVE'];
  const counts=Object.fromEntries(statuses.map(s=>[s,data.research.filter(r=>r.status===s).length]));
  section.innerHTML=`<div class="view-intro"><p class="eyebrow">Research memory engine</p><h1>研究记忆</h1><p>保留支持证据、反证、替代解释和判断变化；不会用新结论覆盖旧判断。</p></div><div class="research-status-grid">${statuses.slice(0,6).map(s=>`<div class="status-stat"><span>${statusText(s)}</span><b>${counts[s]}</b></div>`).join('')}<div class="status-stat"><span>待补数据</span><b>${counts.INCONCLUSIVE + data.research.filter(r=>(r.requiredData||[]).length>0).length}</b></div></div><div class="panel research-list"><div class="panel-title"><div><p class="eyebrow">研究问题</p><h2>${data.research.length} 条可追溯研究</h2></div><button class="primary" id="createResearch">+ 新建研究问题</button></div><div class="research-list-body">${data.research.map(r=>{const x=window.MinshengConfidence.explain(r,data.evidence);return `<button class="research-row" data-research="${r.id}"><div>${badge(r.status)}<b>${r.title}</b><span>${r.currentConclusion}</span></div><div class="research-score"><b>${r.confidence===null?'数据不足':Math.round(r.confidence*100)+'%'}</b><small>支持 ${x.supportScore.toFixed(2)} · 反证 ${x.contradictScore.toFixed(2)}</small></div><span class="chev">→</span></button>`}).join('')}</div></div>`;
  section.querySelectorAll('[data-research]').forEach(el=>el.onclick=()=>openResearchDetail(el.dataset.research));
  byId('createResearch').onclick=openCreateResearch;
}
function evidenceMatches(e) {
  const f=appState.evidenceFilter||'全部', t=appState.evidenceTypeFilter||'全部', source=appState.evidenceSourceFilter||'全部';
  return (f==='全部'||e.stance===f) && (t==='全部'||e.evidenceType===t) && (source==='全部'||e.sourceType===source);
}
function renderEvidenceEngine() {
  const section=byId('evidence');if(!section)return;
  const list=data.evidence.filter(evidenceMatches), stances=['全部','SUPPORT','CONTRADICT','NEUTRAL','CONTEXT'], types=['全部','FACT','ESTIMATE','INFERENCE','FORECAST','OPINION','HYPOTHESIS'], sources=['全部','official_primary','multilateral','investment_bank','academic','market_data','media','social_media','survey'];
  section.classList.remove('placeholder');
  section.innerHTML=`<div class="view-intro"><p class="eyebrow">Evidence & research memory</p><h1>证据库</h1><p>证据不等于真相：来源、证据等级、立场和置信度必须同时阅读。</p></div><div class="evidence-actions"><button class="primary" id="newEvidence">+ 添加证据</button><button class="secondary" id="importJson">导入 JSON</button><button class="secondary" id="importCsv">导入指标 CSV</button><button class="secondary" id="exportSnapshot">导出研究快照</button><button class="secondary danger" id="resetDemo">恢复 DEMO 数据</button><input id="jsonInput" type="file" accept="application/json" hidden><input id="csvInput" type="file" accept=".csv,text/csv" hidden></div><section class="panel evidence-table"><div class="evidence-filters"><div>${stances.map(x=>`<button data-stance="${x}" class="${(appState.evidenceFilter||'全部')===x?'selected':''}">${x}</button>`).join('')}</div><select id="evidenceTypeSelect">${types.map(x=>`<option ${((appState.evidenceTypeFilter||'全部')===x)?'selected':''}>${x}</option>`).join('')}</select><select id="evidenceSourceSelect">${sources.map(x=>`<option ${((appState.evidenceSourceFilter||'全部')===x)?'selected':''}>${x}</option>`).join('')}</select></div><table><thead><tr><th>证据</th><th>立场</th><th>来源</th><th>等级 / 置信度</th><th>新鲜度</th><th>关联研究</th></tr></thead><tbody>${list.map(e=>`<tr data-evidence="${e.id}"><td><b>${e.title} ${e.status==='MOCK'?'<span class="demo-flag">MOCK</span>':''}</b><small>${e.summary}</small></td><td><span class="stance ${e.stance.toLowerCase()}">${e.stance}</span></td><td>${sourceOf(e.sourceId).name}<small>${e.sourceType}</small></td><td>${badge(e.evidenceType)}<small>${Math.round(e.confidence*100)}% · 重要度 ${Math.round(e.importance*100)}%</small></td><td>${freshnessLabel(e.publishedAt)}</td><td>${e.relatedResearch.map(id=>data.research.find(r=>r.id===id)?.title||id).join('；') || '—'}</td></tr>`).join('')}</tbody></table></section><section class="panel inbox"><div class="panel-title"><div><p class="eyebrow">Evidence Inbox</p><h2>待整理区</h2></div><span class="demo-flag">MOCK INBOX</span></div><div class="inbox-list">${data.inbox.map(item=>`<div class="inbox-item"><div><b>${item.title}</b><p>${item.rawText}</p><small>${sourceOf(item.sourceId).name} · 接收 ${fmtDate(item.receivedAt)}</small></div><select data-inbox="${item.id}">${['NEW','REVIEWED','LINKED','REJECTED'].map(s=>`<option ${item.reviewStatus===s?'selected':''}>${s}</option>`).join('')}</select></div>`).join('')}</div></section>`;
  section.querySelectorAll('[data-stance]').forEach(btn=>btn.onclick=()=>{appState.evidenceFilter=btn.dataset.stance;renderEvidenceEngine()});
  byId('evidenceTypeSelect').onchange=e=>{appState.evidenceTypeFilter=e.target.value;renderEvidenceEngine()}; byId('evidenceSourceSelect').onchange=e=>{appState.evidenceSourceFilter=e.target.value;renderEvidenceEngine()};
  section.querySelectorAll('[data-evidence]').forEach(row=>row.onclick=()=>openEvidenceDetail(row.dataset.evidence)); section.querySelectorAll('[data-inbox]').forEach(select=>select.onchange=()=>{data.inbox.find(i=>i.id===select.dataset.inbox).reviewStatus=select.value;saveLocalResearch()});
  byId('newEvidence').onclick=()=>openEvidenceForm(); byId('importJson').onclick=()=>byId('jsonInput').click(); byId('importCsv').onclick=()=>byId('csvInput').click(); byId('exportSnapshot').onclick=exportSnapshot; byId('resetDemo').onclick=resetDemo; byId('jsonInput').onchange=importJsonFile; byId('csvInput').onchange=importCsvFile;
}
function freshnessLabel(date) {const value=window.MinshengConfidence.freshnessWeight(date);return value===1?'高（0—3个月）':value===.75?'中（3—12个月）':'低（12个月以上）';}
function openEvidenceDetail(id) {const e=data.evidence.find(x=>x.id===id);if(!e)return;openDialog(`<p class="eyebrow">证据详情 ${e.status==='MOCK'?'<span class="demo-flag">MOCK</span>':''}</p><h2>${e.title}</h2><div class="detail-copy">${e.summary}</div><p>${badge(e.evidenceType)} <span class="stance ${e.stance.toLowerCase()}">${e.stance}</span></p><div class="detail-grid"><div><b>来源</b><span>${sourceOf(e.sourceId).name}</span></div><div><b>来源类型</b><span>${e.sourceType}</span></div><div><b>发布日期 / 数据期</b><span>${fmtDate(e.publishedAt)} / ${e.dataPeriod||'数据不足'}</span></div><div><b>置信度 / 重要度</b><span>${Math.round(e.confidence*100)}% / ${Math.round(e.importance*100)}%</span></div><div><b>新鲜度</b><span>${freshnessLabel(e.publishedAt)}</span></div><div><b>来源链接</b><span>${e.url?e.url:'暂无来源链接'}</span></div></div><p class="detail-copy"><b>关联研究：</b>${e.relatedResearch.map(id=>data.research.find(r=>r.id===id)?.title||id).join('；')||'—'}<br><b>关联指标：</b>${e.relatedIndicators.map(id=>indicatorOf(id)?.name||id).join('；')||'—'}<br><b>备注：</b>${e.notes||'—'}</p>`);}
function openResearchDetail(id) {const r=data.research.find(x=>x.id===id);if(!r)return;const x=window.MinshengConfidence.explain(r,data.evidence), related=data.evidence.filter(e=>e.relatedResearch.includes(r.id));const evidenceList=(stance,label)=>{const items=related.filter(e=>e.stance===stance);return `<div class="research-evidence"><b>${label}（${items.length}）</b>${items.length?items.map(e=>`<button data-evidence-open="${e.id}">${badge(e.evidenceType)} ${e.title}<small>${sourceOf(e.sourceId).name} · ${Math.round(e.confidence*100)}%</small></button>`).join(''):'<p>暂无</p>'}</div>`};const timeline=[{date:r.createdAt,reason:'研究创建',newConfidence:r.history?.[0]?.previousConfidence??r.confidence},...(r.history||[])];openDialog(`<p class="eyebrow">研究详情</p><h2>${r.title}</h2><p>${badge(r.status)} <button class="confidence-link" id="showConfidence">当前置信度 ${r.confidence===null?'数据不足':Math.round(r.confidence*100)+'%'}</button></p><div class="detail-copy"><b>当前结论</b><br>${r.currentConclusion}</div><div class="hypothesis-box"><b>研究假设</b><p>${r.hypothesis}</p></div><div class="research-evidence-grid">${evidenceList('SUPPORT','支持证据')}${evidenceList('CONTRADICT','反对证据')}${evidenceList('NEUTRAL','中性证据')}${evidenceList('CONTEXT','背景材料')}</div><h3>替代假设</h3><div class="alternatives">${r.alternativeHypotheses.map(a=>`<div><b>${a.title}</b><p>${a.description}</p></div>`).join('')||'<p>暂无'}</div><button class="secondary" id="addAlternative">+ 添加替代假设</button><h3>缺失数据</h3><ul class="required-data">${r.requiredData.map(x=>`<li>${x}</li>`).join('')||'<li>数据不足</li>'}</ul><h3>判断演化</h3><div class="timeline">${timeline.map(h=>`<div><span>${fmtDate(h.date)}</span><b>${h.newConfidence===null?'数据不足':Math.round(h.newConfidence*100)+'%'}</b><p>${h.reason}</p></div>`).join('')}</div><div class="modal-actions"><button class="secondary" id="addResearchEvidence">+ 添加证据</button><button class="primary close">关闭</button></div>`);const modal=byId('modal');modal.querySelectorAll('[data-evidence-open]').forEach(btn=>btn.onclick=()=>openEvidenceDetail(btn.dataset.evidenceOpen));byId('showConfidence').onclick=()=>openConfidenceDetail(r.id);byId('addResearchEvidence').onclick=()=>openEvidenceForm(r.id);byId('addAlternative').onclick=()=>openAlternativeForm(r.id);modal.querySelector('.close').onclick=()=>modal.classList.remove('show');}
function openConfidenceDetail(id){const r=data.research.find(x=>x.id===id),x=window.MinshengConfidence.explain(r,data.evidence);openDialog(`<p class="eyebrow">透明规则评分 · DEMO</p><h2>置信度解释</h2><div class="score-explain"><div><b>当前支持分</b><span>${x.supportScore.toFixed(2)}</span></div><div><b>当前反证分</b><span>${x.contradictScore.toFixed(2)}</span></div><div><b>净证据</b><span>${x.netEvidence>=0?'+':''}${x.netEvidence.toFixed(2)}</span></div></div><p class="detail-copy">Evidence Score = 来源权重 × 证据类型权重 × 置信度 × 重要度 × 新鲜度。</p><p class="detail-copy">本评分来自民生OS当前透明规则，不代表统计显著性或科学概率。</p><div class="weight-grid"><div><b>主要支持</b><p>${x.support.map(e=>sourceOf(e.sourceId).name+'：'+e.title).join('<br>')||'暂无'}</p></div><div><b>主要反证</b><p>${x.contradict.map(e=>sourceOf(e.sourceId).name+'：'+e.title).join('<br>')||'暂无'}</p></div></div>`);}
function openEvidenceForm(researchId='') {const sources=data.sources.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');openDialog(`<p class="eyebrow">手动添加证据</p><h2>记录一条可追溯材料</h2><form id="evidenceForm"><label>证据标题<input name="title" required></label><label>摘要<textarea name="summary" required></textarea></label><div class="form-two"><label>来源<select name="sourceId">${sources}</select></label><label>证据等级<select name="evidenceType">${window.MinshengImportExport.evidenceTypes.map(t=>`<option>${t}</option>`).join('')}</select></label></div><div class="form-two"><label>立场<select name="stance"><option>SUPPORT</option><option>CONTRADICT</option><option>NEUTRAL</option><option>CONTEXT</option></select></label><label>置信度（0—1）<input name="confidence" type="number" min="0" max="1" step=".01" value="0.6"></label></div><label>重要度（0—1）<input name="importance" type="number" min="0" max="1" step=".01" value="0.5"></label><button class="primary">保存证据</button></form>`);byId('evidenceForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));const item={id:'user_evidence_'+Date.now(),title:v.title,summary:v.summary,sourceId:v.sourceId,sourceType:sourceOf(v.sourceId).type,evidenceType:v.evidenceType,stance:v.stance,confidence:Number(v.confidence),importance:Number(v.importance),publishedAt:window.MinshengResearchMemory.today(),dataPeriod:null,url:'',relatedIndicators:[],relatedResearch:researchId?[researchId]:[],tags:['手动添加'],status:'LOCAL',notes:''};const error=window.MinshengImportExport.validateEvidence(item);if(error){alert(error);return}data.evidence.push(item);if(researchId){const r=data.research.find(x=>x.id===researchId);window.MinshengResearchMemory.linkEvidence(r,item);const x=window.MinshengConfidence.explain(r,data.evidence);const newConfidence=Math.max(.05,Math.min(.95,(r.confidence??.35)+x.netEvidence*.1));window.MinshengResearchMemory.appendHistory(r,{newConfidence,newConclusion:r.currentConclusion,reason:`新增${item.stance==='CONTRADICT'?'反对':'支持/背景'}证据：${item.title}`,addedEvidenceIds:[item.id]});}saveLocalResearch();renderEvidenceEngine();renderResearchWorkspace();renderResearchNotes();byId('modal').classList.remove('show');};}
function openAlternativeForm(researchId){openDialog(`<p class="eyebrow">替代假设</p><h2>避免只寻找单一解释</h2><form id="alternativeForm"><label>标题<input name="title" required></label><label>说明<textarea name="description" required></textarea></label><button class="primary">保存替代假设</button></form>`);byId('alternativeForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target)),r=data.research.find(x=>x.id===researchId);r.alternativeHypotheses.push({id:'alt_'+Date.now(),...v});saveLocalResearch();openResearchDetail(researchId);renderResearchWorkspace();};}
function openCreateResearch(){openDialog(`<p class="eyebrow">新建研究问题</p><h2>定义可被反驳的假设</h2><form id="researchForm"><label>标题<input name="title" required></label><label>研究领域<input name="category" required placeholder="例如：居民部门"></label><label>初始假设<textarea name="hypothesis" required></textarea></label><label>初始置信度（0—1）<input name="confidence" type="number" min="0" max="1" step=".01" value="0.3"></label><label>所需数据（每行一项）<textarea name="requiredData"></textarea></label><button class="primary">创建研究问题</button></form>`);byId('researchForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target)),r={id:'user_research_'+Date.now(),title:v.title,category:v.category,status:'HYPOTHESIS',hypothesis:v.hypothesis,currentConclusion:'初始假设，数据不足，等待证据进入。',confidence:Number(v.confidence),evidenceIds:[],contradictingEvidenceIds:[],alternativeHypotheses:[],requiredData:v.requiredData.split('\n').map(x=>x.trim()).filter(Boolean),createdAt:window.MinshengResearchMemory.today(),updatedAt:window.MinshengResearchMemory.today(),history:[]};data.research.push(r);saveLocalResearch();renderResearchWorkspace();byId('modal').classList.remove('show');showView('research');};}
function exportSnapshot(){window.MinshengImportExport.download('minsheng-os-research-snapshot.json',{version:'0.3',exportedAt:new Date().toISOString(),research:data.research,evidence:data.evidence,indicators:data.indicators,localState:{inbox:data.inbox}});}
function resetDemo(){if(!confirm('将清除本地研究修改并恢复 DEMO 数据，是否继续？'))return;window.MinshengPersistence.clear();data.research=window.MinshengPersistence.clone(baseData.research);data.evidence=window.MinshengPersistence.clone(baseData.evidence);data.inbox=window.MinshengPersistence.clone(baseData.inbox);data.indicators=window.MinshengPersistence.clone(baseData.indicators);renderEvidenceEngine();renderResearchWorkspace();renderResearchNotes();}
function importJsonFile(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const parsed=window.MinshengImportExport.parseJson(reader.result);if(parsed.errors.length){alert(parsed.errors.join('\n'));return}const incoming=parsed.value, errors=[], collections=[['evidence',window.MinshengImportExport.validateEvidence],['research',window.MinshengImportExport.validateResearch],['indicators',x=>x?.id?null:'指标必须包含 id。']];collections.forEach(([key,validator])=>(incoming[key]||[]).forEach(item=>{const target=data[key];if(!Array.isArray(target))return;if(target.some(x=>x.id===item.id))errors.push(`${key}: 重复 id ${item.id}`);const err=validator(item);if(err)errors.push(`${key}: ${err}`)}));if(errors.length){alert('导入失败：\n'+errors.join('\n'));return}collections.forEach(([key])=>{if(Array.isArray(incoming[key]))data[key].push(...incoming[key])});saveLocalResearch();renderEvidenceEngine();renderResearchWorkspace();alert('JSON 导入完成。');};reader.readAsText(file);}
function importCsvFile(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const result=window.MinshengImportExport.parseCsv(reader.result);if(result.errors.length){alert('CSV 导入失败：\n'+result.errors.join('\n'));return}openDialog(`<p class="eyebrow">CSV 预览</p><h2>确认导入指标</h2><p class="detail-copy">将导入 ${result.rows.length} 条；以下仅预览前 10 行。</p><pre class="csv-preview">${JSON.stringify(result.rows.slice(0,10),null,2)}</pre><button class="primary" id="confirmCsv">确认导入</button>`);byId('confirmCsv').onclick=()=>{const duplicate=result.rows.find(row=>data.indicators.some(x=>x.id===row.id));if(duplicate){alert('导入失败：重复 id '+duplicate.id);return}data.indicators.push(...result.rows.map(row=>({...row,value:row.value===''?null:row.value,previousValue:null,category:'imported',module:'导入指标',frequency:'unknown',sourceName:sourceOf(row.sourceId).name,confidence:null,direction:'unknown',status:'LOCAL',updatedAt:window.MinshengResearchMemory.today(),description:'CSV 手动导入',interpretation:'数据待核验。',tags:['CSV 导入'],dataQuality:{completeness:null,freshness:null,reliability:null,comparability:null}})));saveLocalResearch();byId('modal').classList.remove('show');alert('CSV 指标导入完成。');};};reader.readAsText(file);}
function renderResearchNotes() {
  const map=document.querySelector('.system-map');if(!map)return;document.querySelector('.research-notes')?.remove();document.querySelector('.research-dashboard')?.remove();
  const counts={open:data.research.filter(r=>r.status==='OPEN'||r.status==='HYPOTHESIS').length,disputed:data.research.filter(r=>r.status==='DISPUTED'||r.status==='WEAKENED').length,insufficient:data.research.filter(r=>r.confidence===null).length};
  map.insertAdjacentHTML('afterend',`<section class="panel research-dashboard"><div class="panel-title"><div><p class="eyebrow">研究状态 · DEMO / LOCAL</p><h2>当前研究记忆</h2></div><button class="text-btn" data-target="research">打开研究工作台 →</button></div><div class="dashboard-status"><span>开放研究 <b>${counts.open}</b></span><span>存在争议 <b>${counts.disputed}</b></span><span>数据不足 <b>${counts.insufficient}</b></span><span>证据记录 <b>${data.evidence.length}</b></span></div></section><section class="panel research-notes"><div class="panel-title"><div><p class="eyebrow">当前重点研究问题</p><h2>等待证据回答，而非预设结论</h2></div><button class="text-btn" data-target="evidence">研究透明度 →</button></div><div class="notes-grid">${data.research.map(note=>`<button class="research-note" data-note="${note.id}">${badge(note.status)}<b>${note.title}</b><span>置信度 ${note.confidence===null?'数据不足':Math.round(note.confidence*100)+'%'} · 需 ${(note.requiredData||[]).length} 类数据</span></button>`).join('')}</div></section>`);
  map.parentElement.querySelectorAll('[data-target]').forEach(button=>{if(['research','evidence'].includes(button.dataset.target))button.onclick=()=>showView(button.dataset.target)});map.parentElement.querySelectorAll('[data-note]').forEach(note=>note.onclick=()=>openResearchDetail(note.dataset.note));
}
function openIndicatorDetail(indicatorId) {
  const item=indicatorOf(indicatorId); if(!item)return; const source=sourceOf(item.sourceId), score=qualityScore(item.dataQuality);
  openDialog(`<p class="eyebrow">指标证据卡 ${demoFlag(item.status)}</p><h2>${item.name}</h2><div class="detail-value">${item.value} <small>${item.unit}</small></div>${badge(item.evidenceType)}<div class="detail-grid"><div><b>统计周期</b><span>${item.period} · ${item.frequency}</span></div><div><b>来源</b><span>${source.name} / ${source.type}</span></div><div><b>更新时间</b><span>${fmtDate(item.updatedAt)}</span></div><div><b>研究置信度</b><span>${Math.round(item.confidence*100)}%</span></div><div><b>数据质量</b><span>${qualityLabel(score)} ${score}%</span></div><div><b>趋势</b><span>${item.direction}</span></div></div><p class="detail-copy">${item.description}</p><p class="detail-copy"><b>研究提示：</b>${item.interpretation}</p>`);
}
function openIntelligenceDetail(id) { const item=data.intelligence.find(x=>x.id===id); if(!item)return; const source=sourceOf(item.sourceId); openDialog(`<p class="eyebrow">情报证据卡</p><h2>${item.title}</h2>${badge(item.evidenceType)}<p class="detail-copy">${item.summary}</p><div class="detail-grid"><div><b>来源</b><span>${source.name}</span></div><div><b>发布时间</b><span>${fmtDate(item.publishedAt)}</span></div><div><b>事件日期</b><span>${fmtDate(item.eventDate)}</span></div><div><b>置信度</b><span>${Math.round(item.confidence*100)}%</span></div></div><p class="detail-copy"><b>关联模块：</b>${item.relatedModules.join(' · ')}<br><b>关联指标：</b>${item.relatedIndicators.map(id=>indicatorOf(id)?.name || id).join(' · ')}</p>`); }
function openDialog(content) { const modal=byId('modal'); modal.querySelector('.modal').innerHTML=`<button class="close">×</button>${content}`; modal.classList.add('show'); modal.querySelector('.close').onclick=()=>modal.classList.remove('show'); }
function bindStaticEvents() {
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
  document.querySelectorAll('[data-target]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.target)));
  const modal=byId('modal'); byId('newResearch').onclick=()=>openDialog(`<p class="eyebrow">新建研究</p><h2>定义一个可验证的问题</h2><label>研究问题<input placeholder="例如：不同城市的政策传导为何分化？" autofocus></label><label>初始证据类型<select><option>官方一手数据</option><option>官方报告</option><option>调查数据</option><option>市场数据</option></select></label><button class="primary close">创建研究卡片</button>`); modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('show')});
}
function openIndicatorDetail(indicatorId) {
  const item=indicatorOf(indicatorId);if(!item)return;const source=sourceOf(item.sourceId),score=qualityScore(item.dataQuality), relatedEvidence=data.evidence.filter(e=>e.relatedIndicators.includes(item.id)), relatedResearch=data.research.filter(r=>data.evidence.some(e=>e.relatedResearch.includes(r.id)&&e.relatedIndicators.includes(item.id))), relatedRelations=data.relationships.filter(r=>r.from===item.id||r.to===item.id);
  openDialog(`<p class="eyebrow">指标证据卡 ${demoFlag(item.status)}</p><h2>${item.name}</h2><div class="detail-value">${item.value ?? '数据不足'} <small>${item.unit||''}</small></div>${badge(item.evidenceType)}<div class="detail-grid"><div><b>统计周期</b><span>${item.period||'数据不足'} · ${item.frequency||'unknown'}</span></div><div><b>来源</b><span>${source.name} / ${source.type}</span></div><div><b>更新时间</b><span>${fmtDate(item.updatedAt)}</span></div><div><b>研究置信度</b><span>${item.confidence===null?'数据不足':Math.round(item.confidence*100)+'%'}</span></div><div><b>数据质量</b><span>${item.dataQuality?qualityLabel(score)+' '+score+'%':'数据不足'}</span></div><div><b>趋势</b><span>${item.direction||'unknown'}</span></div></div><p class="detail-copy">${item.description||'—'}</p><div class="indicator-links"><b>相关证据 ${relatedEvidence.length}</b>${relatedEvidence.map(e=>`<button data-indicator-evidence="${e.id}">${e.title}</button>`).join('')||'<p>暂无</p>'}<b>相关研究 ${relatedResearch.length}</b>${relatedResearch.map(r=>`<button data-indicator-research="${r.id}">${r.title}</button>`).join('')||'<p>暂无</p>'}<b>相关因果关系 ${relatedRelations.length}</b><p>${relatedRelations.map(r=>`${indicatorOf(r.from)?.name} → ${indicatorOf(r.to)?.name}`).join('<br>')||'暂无'}</p></div>`);
  const modal=byId('modal');modal.querySelectorAll('[data-indicator-evidence]').forEach(b=>b.onclick=()=>openEvidenceDetail(b.dataset.indicatorEvidence));modal.querySelectorAll('[data-indicator-research]').forEach(b=>b.onclick=()=>openResearchDetail(b.dataset.indicatorResearch));
}
function importJsonFile(event) {
  const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const parsed=window.MinshengImportExport.parseJson(reader.result);if(parsed.errors.length){alert(parsed.errors.join('\n'));return}const incoming=parsed.value,errors=[],collections=[['evidence',window.MinshengImportExport.validateEvidence],['research',window.MinshengImportExport.validateResearch],['indicators',item=>item?.id?null:'指标必须包含 id。']];collections.forEach(([key,validate])=>{const seen=new Set(data[key].map(item=>item.id));(incoming[key]||[]).forEach(item=>{if(seen.has(item.id))errors.push(`${key}: 重复 id ${item.id}`);seen.add(item.id);const error=validate(item);if(error)errors.push(`${key}: ${error}`);});});if(errors.length){alert('导入失败：\n'+errors.join('\n'));return}collections.forEach(([key])=>{if(Array.isArray(incoming[key]))data[key].push(...incoming[key])});saveLocalResearch();renderEvidenceEngine();renderResearchWorkspace();renderResearchNotes();alert('JSON 导入完成。');};reader.readAsText(file);
}
function importCsvFile(event) {
  const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const result=window.MinshengImportExport.parseCsv(reader.result);if(result.errors.length){alert('CSV 导入失败：\n'+result.errors.join('\n'));return}openDialog(`<p class="eyebrow">CSV 预览</p><h2>确认导入指标</h2><p class="detail-copy">将导入 ${result.rows.length} 条；以下仅预览前 10 行。</p><pre class="csv-preview">${JSON.stringify(result.rows.slice(0,10),null,2)}</pre><button class="primary" id="confirmCsv">确认导入</button>`);byId('confirmCsv').onclick=()=>{const seen=new Set(data.indicators.map(item=>item.id)), duplicate=result.rows.find(row=>seen.has(row.id)||(seen.add(row.id),false));if(duplicate){alert('导入失败：重复 id '+duplicate.id);return}data.indicators.push(...result.rows.map(row=>({...row,value:row.value===''?null:row.value,previousValue:null,category:'imported',module:'导入指标',frequency:'unknown',sourceName:sourceOf(row.sourceId).name,confidence:null,direction:'unknown',status:'LOCAL',updatedAt:window.MinshengResearchMemory.today(),description:'CSV 手动导入',interpretation:'数据待核验。',tags:['CSV 导入'],dataQuality:{completeness:null,freshness:null,reliability:null,comparability:null}})));saveLocalResearch();byId('modal').classList.remove('show');alert('CSV 指标导入完成。');};};reader.readAsText(file);
}
function audit(action,entityType,entityId,before,after,reason='') { const entry=window.MinshengAuditLog.create(action,entityType,entityId,before,after,reason);window.MinshengAuditLog.add(data.auditLog,entry);return entry; }
function canonicalRecord(indicatorId,period) { const indicator=indicatorOf(indicatorId), targetPeriod=period||indicator?.period; return window.MinshengProvenance.canonical(data.records,data.sources,indicatorId,targetPeriod,data.canonicalOverrides?.[`${indicatorId}|${targetPeriod}`]); }
function hydrateIndicatorsFromRecords() { data.indicators.forEach(indicator=>{const record=canonicalRecord(indicator.id);if(!record)return;indicator.value=record.convertedValue??record.value;indicator.unit=record.convertedUnit??record.unit;indicator.period=record.period;indicator.updatedAt=record.releaseDate;indicator._recordId=record.id;});data.evidence.forEach(e=>{if(e.evidenceType==='FACT'&&!e.dataRecordIds?.length)e.dataRecordIds=data.records.filter(r=>e.relatedIndicators.includes(r.indicatorId)).map(r=>r.id);}); }
function createV04Views() { const evidenceNav=document.querySelector('.nav-item[data-view="evidence"]');if(evidenceNav&&!document.querySelector('.nav-item[data-view="intake"]'))evidenceNav.insertAdjacentHTML('afterend','<button class="nav-item" data-view="intake"><i>⇩</i>数据接入</button><button class="nav-item" data-view="sources"><i>◫</i>来源与血缘</button>');if(!byId('intake'))byId('scenarios').insertAdjacentHTML('beforebegin','<section id="intake" class="view"></section><section id="sources" class="view"></section>'); }
function renderDataHealth() { const map=document.querySelector('.system-map');if(!map)return;document.querySelector('.data-health')?.remove();const h=window.MinshengProvenance.health(data.records),pending=data.inbox.filter(x=>x.reviewStatus==='NEW').length;map.insertAdjacentHTML('afterend',`<section class="panel data-health"><div class="panel-title"><div><p class="eyebrow">Data Health · DEMO / LOCAL</p><h2>数据健康</h2></div><button class="text-btn" data-target="intake">进入数据接入 →</button></div><div class="health-grid"><span>有效记录 <b>${h.valid}</b></span><span>缺失记录 <b>${h.missing}</b></span><span>来源冲突 <b>${h.conflicts}</b></span><span>数据修订 <b>${h.revised}</b></span><span>异常值 <b>${h.outliers}</b></span><span>待审核 <b>${pending}</b></span></div></section>`);map.parentElement.querySelector('.data-health [data-target]').onclick=()=>showView('intake'); }
function renderDataIntake() { const section=byId('intake');if(!section)return;const conflicts=data.records.filter(r=>r.qualityFlags?.includes('SOURCE_CONFLICT')).length;section.innerHTML=`<div class="view-intro"><p class="eyebrow">Data Intake & Provenance</p><h1>数据接入</h1><p>导入前映射字段、校验口径与单位、检查重复/修订/来源冲突；不会静默覆盖既有数字。</p></div><section class="panel intake-steps"><div><b>01</b><span>选择 CSV / JSON</span></div><i>→</i><div><b>02</b><span>字段映射与来源</span></div><i>→</i><div><b>03</b><span>预览与冲突检查</span></div><i>→</i><div><b>04</b><span>生成批次与血缘</span></div></section><div class="intake-actions"><button class="primary" id="intakeCsv">导入 CSV 数据记录</button><button class="secondary" id="intakeJson">导入 JSON 数据记录</button><input id="intakeCsvInput" hidden type="file" accept=".csv,text/csv"><input id="intakeJsonInput" hidden type="file" accept="application/json"></div><div class="intake-grid"><section class="panel"><p class="eyebrow">最近导入</p><h2>导入批次</h2><div class="batch-list">${data.batches.slice().reverse().map(b=>`<div><b>${b.fileName}</b><span>${b.fileType} · ${fmtDate(b.importedAt?.slice(0,10))}</span><small>记录 ${b.recordCount} · 接收 ${b.acceptedCount} · 拒绝 ${b.rejectedCount}</small><em>${b.status}</em></div>`).join('')||'<p>暂无导入批次</p>'}</div></section><section class="panel"><p class="eyebrow">需要关注</p><h2>导入状态</h2><div class="intake-summary"><span>记录总数 <b>${data.records.length}</b></span><span>来源冲突 <b>${conflicts}</b></span><span>指标草稿 <b>${data.indicators.filter(i=>i.status==='DRAFT').length}</b></span><span>审计事件 <b>${data.auditLog.length}</b></span></div><p class="detail-copy">缺失值使用 <code>null</code> 与缺失原因；不会以 0 代替未知。</p></section></div>`;byId('intakeCsv').onclick=()=>byId('intakeCsvInput').click();byId('intakeJson').onclick=()=>byId('intakeJsonInput').click();byId('intakeCsvInput').onchange=e=>prepareCsvIntake(e.target.files[0]);byId('intakeJsonInput').onchange=e=>prepareRecordJsonIntake(e.target.files[0]); }
function genericCsv(text) { const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)return {headers:[],rows:[],errors:['CSV 至少需要标题行和一条数据。']};const split=line=>line.split(',').map(v=>v.trim().replace(/^"|"$/g,''));const headers=split(lines.shift());return {headers,rows:lines.map(split).map(cells=>Object.fromEntries(headers.map((h,i)=>[h,cells[i]??'']))),errors:[]}; }
function mappedDefault(header) { const h=header.toLowerCase();if(/指标|indicator|name/.test(h))return 'indicator';if(/报告期|period|date|月份/.test(h))return 'period';if(/数值|value|数值/.test(h))return 'value';if(/单位|unit/.test(h))return 'unit';if(/频率|frequency/.test(h))return 'frequency';if(/来源|source/.test(h))return 'sourceId';return 'ignore'; }
function prepareCsvIntake(file) { if(!file)return;const reader=new FileReader();reader.onload=()=>{const parsed=genericCsv(reader.result);if(parsed.errors.length){alert(parsed.errors.join('\n'));return}openMappingDialog(parsed,file.name);};reader.readAsText(file); }
function openMappingDialog(parsed,fileName) { const targets=['ignore','indicator','period','value','unit','frequency','sourceId'];openDialog(`<p class="eyebrow">CSV 字段映射</p><h2>将原始字段映射到数据记录</h2><p class="detail-copy">${fileName} · ${parsed.rows.length} 行。未知指标将在预览中标记为 DRAFT，不会自动进入正式指标库。</p><div class="mapping-list">${parsed.headers.map(h=>`<label>${h}<select data-map="${h}">${targets.map(t=>`<option value="${t}" ${mappedDefault(h)===t?'selected':''}>${t}</option>`).join('')}</select></label>`).join('')}</div><label>默认来源<select id="mappingSource">${data.sources.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}</select></label><button class="primary" id="previewMappedCsv">预览与校验</button>`);byId('previewMappedCsv').onclick=()=>{const map=Object.fromEntries(parsed.headers.map(h=>[h,document.querySelector(`[data-map="${CSS.escape(h)}"]`).value]));previewMappedRecords(parsed.rows,map,byId('mappingSource').value,fileName);}; }
function makeRecordCandidate(row,map,sourceId,index) { const read=target=>Object.entries(map).find(([,v])=>v===target)?.[0], rawIndicator=row[read('indicator')]?.trim(), existing=data.indicators.find(i=>i.id===rawIndicator||i.name===rawIndicator), draft=existing||{id:`draft_${rawIndicator?.toLowerCase().replace(/[^a-z0-9]+/g,'_')||index}`,name:rawIndicator||'未命名指标',status:'DRAFT',category:'draft',definition:'由 CSV 导入创建的指标草稿，需人工确认。',preferredUnit:row[read('unit')]||null,frequency:row[read('frequency')]||'monthly',observationType:'index',seasonalAdjustment:false,nominalReal:'nominal',cumulative:false,preferredSourceId:sourceId,alternativeSourceIds:[],methodologyNotes:'',comparabilityNotes:'',startPeriod:null,discontinued:false}; const unit=row[read('unit')]||draft.preferredUnit||null,frequency=row[read('frequency')]||draft.frequency||'monthly',conversion=window.MinshengProvenance.normalizeUnit(row[read('value')],unit,draft.preferredUnit||unit), flags=[];if(conversion.flag)flags.push(conversion.flag);if(row[read('value')]==='')flags.push('MISSING');if(!existing)flags.push('DRAFT_INDICATOR');const record={id:`record_import_${Date.now()}_${index}`,seriesId:`LOCAL.${sourceId.toUpperCase()}.${draft.id.toUpperCase()}.${frequency.toUpperCase()}.${draft.observationType?.toUpperCase()||'INDEX'}`,indicatorId:draft.id,value:conversion.value??null,unit:conversion.unit||unit,period:row[read('period')]||null,frequency,observationType:draft.observationType||'index',transformation:'raw',sourceId:row[read('sourceId')]||sourceId,sourceDocumentId:null,releaseDate:window.MinshengResearchMemory.today(),importedAt:new Date().toISOString(),evidenceType:'FACT',status:'LOCAL',revision:0,previousRecordId:null,qualityFlags:flags,originalValue:conversion.originalValue??row[read('value')]??null,originalUnit:conversion.originalUnit??unit,convertedValue:conversion.value??null,convertedUnit:conversion.unit??unit,conversionRule:conversion.rule||null,missingReason:row[read('value')]===''?'not_available':null,provenance:{importBatchId:null,originalFile:null,originalSheet:null,originalRow:index+2,originalColumn:read('value')||null,originalField:read('value')||null,parser:'csv_field_mapping',transformationHistory:conversion.rule?[conversion.rule]:[]},notes:''};return {record,draft,conversion}; }
function previewMappedRecords(rows,map,sourceId,fileName) { const proposed=rows.map((row,index)=>makeRecordCandidate(row,map,sourceId,index));const allIndicators=[...data.indicators,...proposed.filter(x=>!data.indicators.some(i=>i.id===x.draft.id)).map(x=>x.draft)], errors=[], conflicts=[];proposed.forEach(p=>{const e=[...window.MinshengProvenance.validate(p.record,allIndicators,data.sources),p.conversion.error].filter(Boolean);if(e.length)errors.push({p,e});const c=window.MinshengProvenance.classifyConflict(p.record,data.records);if(c.type!=='none')conflicts.push({p,c});p.conflict=c;});const accepted=proposed.length-errors.length-conflicts.filter(x=>x.c.type==='duplicate').length;openDialog(`<p class="eyebrow">导入预览</p><h2>确认数据记录</h2><div class="preview-counts"><span>总记录 <b>${proposed.length}</b></span><span>可导入 <b>${Math.max(0,accepted)}</b></span><span>警告 <b>${conflicts.length}</b></span><span>错误 <b>${errors.length}</b></span></div><p class="detail-copy">同来源同期间数值变化视为修订冲突；不同来源数值不同会同时保留并标记来源冲突。</p>${conflicts.length?`<label>修订冲突处理<select id="revisionAction"><option value="preserve">保留旧值（跳过新值）</option><option value="revise">接受新值作为修订</option></select></label><div class="conflict-list">${conflicts.slice(0,8).map(x=>`<p><b>${x.p.record.indicatorId} / ${x.p.record.period}</b>：${x.c.type}</p>`).join('')}</div>`:''}${errors.length?`<div class="error-list">${errors.slice(0,8).map(x=>`<p>${x.p.record.indicatorId||'未知指标'}：${x.e.join('；')}</p>`).join('')}</div>`:''}<pre class="csv-preview">${JSON.stringify(proposed.slice(0,10).map(x=>x.record),null,2)}</pre><button class="primary" id="commitDataImport">确认正式导入</button>`);byId('commitDataImport').onclick=()=>commitRecordImport({proposed,errors,fileName,sourceId,revisionAction:byId('revisionAction')?.value||'preserve'}); }
function commitRecordImport({proposed,errors,fileName,sourceId,revisionAction}) { const invalid=new Set(errors.map(x=>x.p));const batch={id:`batch_${Date.now()}`,importedAt:new Date().toISOString(),fileName,fileType:'csv',sourceId,recordCount:proposed.length,acceptedCount:0,rejectedCount:0,status:'completed',warnings:[],errors:[]};const drafts=[];proposed.forEach(p=>{if(invalid.has(p)){batch.rejectedCount++;batch.errors.push('Schema validation failed');return}const conflict=window.MinshengProvenance.classifyConflict(p.record,data.records);if(conflict.type==='duplicate'){batch.rejectedCount++;batch.warnings.push(`duplicate: ${p.record.indicatorId} ${p.record.period}`);return}if(conflict.type==='revision_conflict'&&revisionAction!=='revise'){batch.rejectedCount++;batch.warnings.push(`revision preserved: ${p.record.indicatorId} ${p.record.period}`);return}if(!data.indicators.some(i=>i.id===p.draft.id)){drafts.push(p.draft);audit('CREATE_INDICATOR','indicator',p.draft.id,null,p.draft,'CSV unknown indicator created as DRAFT');}p.record.provenance.importBatchId=batch.id;p.record.provenance.originalFile=fileName;if(conflict.type==='revision_conflict'){const prior=conflict.matches.sort((a,b)=>b.revision-a.revision)[0];p.record.revision=prior.revision+1;p.record.previousRecordId=prior.id;p.record.qualityFlags.push('REVISED');audit('REVISE','data_record',p.record.id,prior,p.record,'CSV value changed for same source/indicator/period');}else if(conflict.type==='source_conflict'){p.record.qualityFlags.push('SOURCE_CONFLICT');conflict.matches.forEach(r=>{if(!r.qualityFlags.includes('SOURCE_CONFLICT'))r.qualityFlags.push('SOURCE_CONFLICT')});audit('IMPORT','data_record',p.record.id,null,p.record,'Different source value retained as source conflict');}else audit('IMPORT','data_record',p.record.id,null,p.record,'CSV import');data.records.push(p.record);batch.acceptedCount++;});data.indicators.push(...drafts.filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i));data.batches.push(batch);audit('IMPORT','import_batch',batch.id,null,batch,`Imported ${batch.acceptedCount} records from ${fileName}`);saveLocalResearch();hydrateIndicatorsFromRecords();renderDataIntake();renderDataHealth();renderIndicators();byId('modal').classList.remove('show');alert(`导入完成：接收 ${batch.acceptedCount}，拒绝 ${batch.rejectedCount}。`); }
function prepareRecordJsonIntake(file) { if(!file)return;const reader=new FileReader();reader.onload=()=>{const parsed=window.MinshengImportExport.parseJson(reader.result);if(parsed.errors.length){alert(parsed.errors.join('\n'));return}const records=parsed.value.dataRecords||parsed.value.records;if(!Array.isArray(records)){alert('JSON 必须包含 dataRecords 或 records 数组。');return}const errors=[];records.forEach(r=>errors.push(...window.MinshengProvenance.validate(r,data.indicators,data.sources)));if(errors.length){alert('JSON 数据记录校验失败：\n'+[...new Set(errors)].join('\n'));return}previewMappedRecords(records.map(r=>({indicator:r.indicatorId,period:r.period,value:r.value,unit:r.unit,frequency:r.frequency,sourceId:r.sourceId})),{indicator:'indicator',period:'period',value:'value',unit:'unit',frequency:'frequency',sourceId:'sourceId'},records[0]?.sourceId||'pboc',file.name);};reader.readAsText(file); }
function renderSources() { const section=byId('sources');if(!section)return;const sources=data.sources.map(source=>{const records=data.records.filter(r=>r.sourceId===source.id&&!r.deleted),latest=records.map(r=>r.period).sort().at(-1)||'—',indicators=[...new Set(records.map(r=>r.indicatorId))];return {source,records,latest,indicators};});section.innerHTML=`<div class="view-intro"><p class="eyebrow">Source registry & Data Lineage</p><h1>来源与数据血缘</h1><p>当前采用值可追溯到 Data Record、导入批次、原始字段、转换规则与来源机构。</p></div><div class="source-cards">${sources.map(({source,records,latest,indicators})=>`<button class="panel source-card" data-source="${source.id}"><div><p class="eyebrow">${source.type}</p><h2>${source.name}</h2></div><span class="demo-flag">${source.qualityConfigStatus||'DEMO'}</span><div class="source-stats"><span>数据记录 <b>${records.length}</b></span><span>最新期间 <b>${latest}</b></span><span>关联指标 <b>${indicators.length}</b></span></div><small>权威 ${Math.round(source.authority*100)}% · 透明度 ${Math.round(source.transparency*100)}%</small></button>`).join('')}</div><section class="panel audit-panel"><div class="panel-title"><div><p class="eyebrow">Audit Log</p><h2>近期审计记录</h2></div></div><div class="audit-list">${data.auditLog.slice().reverse().slice(0,10).map(a=>`<div><b>${a.action}</b><span>${a.entityType} · ${a.entityId}</span><small>${a.reason||'—'} · ${fmtDate(a.timestamp.slice(0,10))}</small></div>`).join('')||'<p>暂无本地审计操作；初始 MOCK 记录未计入操作日志。</p>'}</div></section>`;section.querySelectorAll('[data-source]').forEach(button=>button.onclick=()=>openSourceDetail(button.dataset.source)); }
function openSourceDetail(id) { const source=sourceOf(id),records=data.records.filter(r=>r.sourceId===id&&!r.deleted);openDialog(`<p class="eyebrow">来源详情 · DEMO 配置</p><h2>${source.name}</h2><div class="detail-grid"><div><b>类型</b><span>${source.type}</span></div><div><b>数据记录</b><span>${records.length}</span></div><div><b>权威配置</b><span>${Math.round(source.authority*100)}%</span></div><div><b>方法透明度</b><span>${Math.round(source.methodologyClarity*100)}%</span></div></div><h3>关联数据记录</h3><div class="source-records">${records.map(r=>`<button data-record-open="${r.id}">${r.indicatorId} · ${r.period} · ${r.convertedValue??'数据不足'} ${r.convertedUnit||r.unit}</button>`).join('')||'<p>暂无</p>'}</div>`);byId('modal').querySelectorAll('[data-record-open]').forEach(b=>b.onclick=()=>openRecordDetail(b.dataset.recordOpen)); }
function openRecordDetail(id) { const r=data.records.find(x=>x.id===id);if(!r)return;const indicator=indicatorOf(r.indicatorId),batch=data.batches.find(b=>b.id===r.provenance?.importBatchId),document=data.sourceDocuments.find(d=>d.id===r.sourceDocumentId),canonical=canonicalRecord(r.indicatorId,r.period),revisions=data.records.filter(x=>x.indicatorId===r.indicatorId&&x.period===r.period&&x.sourceId===r.sourceId).sort((a,b)=>a.revision-b.revision);openDialog(`<p class="eyebrow">Data Lineage</p><h2>${indicator?.name||r.indicatorId} · ${r.period}</h2><div class="detail-value">${r.convertedValue??'数据不足'} <small>${r.convertedUnit||r.unit||''}</small></div><p>${r.id===canonical?.id?'<span class="metric-chip green">当前采用值</span>':'<span class="metric-chip neutral">备选值</span>'} ${r.status==='MOCK'?'<span class="demo-flag">MOCK</span>':''}</p><div class="lineage-flow"><span>指标<br><b>${indicator?.name||r.indicatorId}</b></span><i>↓</i><span>记录<br><b>${r.id}</b></span><i>↓</i><span>来源<br><b>${sourceOf(r.sourceId).name}</b></span><i>↓</i><span>批次<br><b>${batch?.id||'迁移/手动'}</b></span></div><div class="detail-grid"><div><b>观察期 / 发布日</b><span>${r.period} / ${fmtDate(r.releaseDate)}</span></div><div><b>频率 / 类型</b><span>${r.frequency} / ${r.observationType}</span></div><div><b>转换</b><span>${r.transformation}${r.conversionRule?' · '+r.conversionRule:''}</span></div><div><b>原始字段</b><span>${r.provenance?.originalField||'—'}</span></div><div><b>质量标记</b><span>${r.qualityFlags?.join(' · ')||'—'}</span></div><div><b>统计口径</b><span>${indicator?.methodologyNotes||'未登记'}</span></div></div><h3>修订历史</h3><div class="revision-list">${revisions.map(x=>`<div><b>r${x.revision}</b><span>${x.convertedValue??'数据不足'} ${x.convertedUnit||x.unit} · ${fmtDate(x.releaseDate)}</span></div>`).join('')}</div>${r.id!==canonical?.id?'<button class="secondary" id="setCanonical">将此记录设为当前采用值</button>':''}`);if(byId('setCanonical'))byId('setCanonical').onclick=()=>{data.canonicalOverrides[`${r.indicatorId}|${r.period}`]=r.id;audit('CHANGE_CANONICAL','data_record',r.id,canonical,r,'Manual canonical record selection');saveLocalResearch();hydrateIndicatorsFromRecords();renderIndicators();renderDataIntake();openRecordDetail(r.id);}; }
function openIndicatorDetail(indicatorId) { const item=indicatorOf(indicatorId);if(!item)return;const records=data.records.filter(r=>r.indicatorId===item.id&&!r.deleted).sort((a,b)=>a.period.localeCompare(b.period)),record=canonicalRecord(item.id),evidence=data.evidence.filter(e=>e.relatedIndicators.includes(item.id)),research=data.research.filter(r=>evidence.some(e=>e.relatedResearch.includes(r.id))),relations=data.relationships.filter(r=>r.from===item.id||r.to===item.id);openDialog(`<p class="eyebrow">指标与时间序列 ${demoFlag(item.status)}</p><h2>${item.name}</h2><div class="detail-value">${record?.convertedValue??'数据不足'} <small>${record?.convertedUnit||item.unit||''}</small></div><p>${badge(record?.evidenceType||item.evidenceType)} ${record?`当前记录：${record.id}`:'暂无 Data Record'}</p><div class="series-list">${records.map(r=>`<button data-record-open="${r.id}"><span>${r.period}</span><b>${r.convertedValue??'数据不足'} ${r.convertedUnit||r.unit||''}</b><small>${sourceOf(r.sourceId).name} · r${r.revision}${r.qualityFlags?.length?' · '+r.qualityFlags.join(','):''}</small></button>`).join('')||'<p>数据不足</p>'}</div><div class="indicator-links"><b>相关证据 ${evidence.length}</b>${evidence.map(e=>`<button data-indicator-evidence="${e.id}">${e.title}</button>`).join('')||'<p>暂无</p>'}<b>相关研究 ${research.length}</b>${research.map(r=>`<button data-indicator-research="${r.id}">${r.title}</button>`).join('')||'<p>暂无</p>'}<b>相关因果关系 ${relations.length}</b><p>${relations.map(r=>`${indicatorOf(r.from)?.name} → ${indicatorOf(r.to)?.name}`).join('<br>')||'暂无'}</p></div>`);const modal=byId('modal');modal.querySelectorAll('[data-record-open]').forEach(b=>b.onclick=()=>openRecordDetail(b.dataset.recordOpen));modal.querySelectorAll('[data-indicator-evidence]').forEach(b=>b.onclick=()=>openEvidenceDetail(b.dataset.indicatorEvidence));modal.querySelectorAll('[data-indicator-research]').forEach(b=>b.onclick=()=>openResearchDetail(b.dataset.indicatorResearch)); }
function hydrateIndicatorsFromRecords() { window.MinshengOutliers?.apply(data.records);data.indicators.forEach(indicator=>{const record=canonicalRecord(indicator.id);if(!record)return;indicator.value=record.convertedValue??record.value;indicator.unit=record.convertedUnit??record.unit;indicator.period=record.period;indicator.updatedAt=record.releaseDate;indicator._recordId=record.id;});data.evidence.forEach(e=>{if(e.evidenceType==='FACT'&&!e.dataRecordIds?.length)e.dataRecordIds=data.records.filter(r=>e.relatedIndicators.includes(r.indicatorId)).map(r=>r.id);}); }
function exportSnapshot(){window.MinshengImportExport.download('minsheng-os-v04-snapshot.json',{version:'0.4',exportedAt:new Date().toISOString(),research:data.research,evidence:data.evidence,indicators:data.indicators,dataRecords:data.records,importBatches:data.batches,canonicalOverrides:data.canonicalOverrides,auditLog:data.auditLog,localState:{inbox:data.inbox}});}
function resetDemo(){if(!confirm('将清除本地研究与数据接入修改，并恢复 DEMO / MOCK 数据，是否继续？'))return;window.MinshengPersistence.clear();['research','evidence','inbox','indicators','records','batches','auditLog','canonicalOverrides'].forEach(key=>data[key]=window.MinshengPersistence.clone(baseData[key]));hydrateIndicatorsFromRecords();renderEvidenceEngine();renderResearchWorkspace();renderResearchNotes();renderDataHealth();renderDataIntake();renderSources();renderIndicators();}
function openEvidenceDetail(id) {const e=data.evidence.find(x=>x.id===id);if(!e)return;const records=(e.dataRecordIds||[]).map(id=>data.records.find(r=>r.id===id)).filter(Boolean);openDialog(`<p class="eyebrow">证据详情 ${e.status==='MOCK'?'<span class="demo-flag">MOCK</span>':''}</p><h2>${e.title}</h2><div class="detail-copy">${e.summary}</div><p>${badge(e.evidenceType)} <span class="stance ${e.stance.toLowerCase()}">${e.stance}</span></p><div class="detail-grid"><div><b>来源</b><span>${sourceOf(e.sourceId).name}</span></div><div><b>来源类型</b><span>${e.sourceType}</span></div><div><b>发布日期 / 数据期</b><span>${fmtDate(e.publishedAt)} / ${e.dataPeriod||'数据不足'}</span></div><div><b>置信度 / 重要度</b><span>${Math.round(e.confidence*100)}% / ${Math.round(e.importance*100)}%</span></div><div><b>新鲜度</b><span>${freshnessLabel(e.publishedAt)}</span></div><div><b>来源链接</b><span>${e.url?e.url:'暂无来源链接'}</span></div></div><h3>关联数据记录（${records.length}）</h3><div class="source-records">${records.map(r=>`<button data-record-open="${r.id}">${r.indicatorId} · ${r.period} · ${r.convertedValue??'数据不足'} ${r.convertedUnit||r.unit}</button>`).join('')||'<p>暂无数据记录；事实证据可在后续人工关联。</p>'}</div><p class="detail-copy"><b>关联研究：</b>${e.relatedResearch.map(id=>data.research.find(r=>r.id===id)?.title||id).join('；')||'—'}<br><b>备注：</b>${e.notes||'—'}</p>`);byId('modal').querySelectorAll('[data-record-open]').forEach(b=>b.onclick=()=>openRecordDetail(b.dataset.recordOpen));}
function createV05Views(){const intakeNav=document.querySelector('.nav-item[data-view="intake"]');if(intakeNav&&!document.querySelector('.nav-item[data-view="library"]'))intakeNav.insertAdjacentHTML('afterend','<button class="nav-item" data-view="library"><i>▤</i>资料库</button><button class="nav-item" data-view="methodologies"><i>⌁</i>统计口径</button>');if(!byId('library'))byId('scenarios').insertAdjacentHTML('beforebegin','<section id="library" class="view"></section><section id="methodologies" class="view"></section>');}
function v05Migrate(){data.records.forEach(r=>{r.deleted??=false;r.deletedAt??=null;r.deleteReason??=null;r.sourceDocumentId??=(r.sourceId==='pboc'?'doc_pboc_2026_07_financial_stats':r.sourceId==='nbs'?'doc_nbs_2026_07_property_stats':null);r.methodologyId??=(r.indicatorId==='household_deposit'?'method_pboc_household_deposit_v1':r.indicatorId==='second_hand_home_price'?'method_nbs_property_price_v2':null);});data.evidence.forEach(e=>{e.sourceDocumentId??=(e.sourceId==='pboc'?'doc_pboc_2026_07_financial_stats':null);e.locator??={page:null,section:'',table:'',row:'',column:'',paragraph:'',quote:null};e.independenceGroup??=(e.sourceDocumentId||`${e.sourceId}_${e.publishedAt}`);});data.sourceDocuments.forEach(d=>{d.deleted??=false;d.deletedAt??=null;d.deleteReason??=null;});}
function renderLibrary(){const section=byId('library');if(!section)return;const query=(appState.documentQuery||'').toLowerCase(),type=appState.documentType||'全部',docs=data.sourceDocuments.filter(d=>!d.deleted&&(type==='全部'||d.documentType===type)&&(!query||[d.title,d.sourceId,...(d.tags||[]),...(d.relatedIndicatorIds||[])].join(' ').toLowerCase().includes(query)));section.innerHTML=`<div class="view-intro"><p class="eyebrow">Source Document Intelligence</p><h1>资料库</h1><p>文件登记不等于证据。文档、数据记录、证据和研究保持独立且可双向追溯。</p></div><div class="library-tools"><input id="documentSearch" placeholder="搜索标题、标签、机构或关联指标" value="${appState.documentQuery||''}"><select id="documentType"><option>全部</option>${['statistical_release','policy_report','research_report','dataset','methodology_document','investment_bank_report','academic_paper','other'].map(x=>`<option ${type===x?'selected':''}>${x}</option>`).join('')}</select><button class="primary" id="registerDocument">+ 登记资料</button></div><div class="library-layout"><section class="panel document-list">${docs.map(d=>`<button data-document="${d.id}"><span class="doc-type">${d.documentType}</span><b>${d.title}</b><small>${sourceOf(d.sourceId).name} · 发布 ${fmtDate(d.publicationDate)} · v${d.version}</small><em>${d.status}</em></button>`).join('')||'<p>无匹配资料。</p>'}</section><aside class="panel library-note"><p class="eyebrow">Document discipline</p><h2>资料定位</h2><p>原始 URL、附件、页码、表格与引文不存在时，系统显示“未登记”，不会编造。</p><div class="doc-coverage"><span>资料 ${data.sourceDocuments.filter(d=>!d.deleted).length}</span><span>附件元数据 ${data.files.filter(f=>!f.deleted).length}</span><span>有文档记录 ${data.records.filter(r=>r.sourceDocumentId&&!r.deleted).length}</span></div></aside></div>`;byId('documentSearch').oninput=e=>{appState.documentQuery=e.target.value;renderLibrary()};byId('documentType').onchange=e=>{appState.documentType=e.target.value;renderLibrary()};byId('registerDocument').onclick=openDocumentForm;section.querySelectorAll('[data-document]').forEach(b=>b.onclick=()=>openDocumentDetail(b.dataset.document));}
function openDocumentForm(){openDialog(`<p class="eyebrow">Document Intake</p><h2>登记资料元数据</h2><form id="documentForm"><label>文件标题<input name="title" required></label><div class="form-two"><label>来源<select name="sourceId">${data.sources.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}</select></label><label>文件类型<select name="documentType">${['statistical_release','policy_report','research_report','dataset','methodology_document','other'].map(x=>`<option>${x}</option>`).join('')}</select></label></div><div class="form-two"><label>发布日期<input name="publicationDate" type="date"></label><label>数据期开始<input name="dataPeriodStart" type="date"></label></div><label>关联指标（以逗号分隔 ID）<input name="indicators" placeholder="household_deposit,mortgage_growth"></label><label>选择附件（仅登记元数据）<input name="attachment" type="file" accept=".pdf,.csv,.json,.txt,.html,.htm,.xlsx,.xls"></label><button class="primary">保存资料登记</button></form>`);byId('documentForm').onsubmit=e=>{e.preventDefault();const form=e.target,v=Object.fromEntries(new FormData(form)),file=form.attachment.files[0],id=`doc_local_${Date.now()}`,doc={id,title:v.title,sourceId:v.sourceId,sourceType:sourceOf(v.sourceId).type,documentType:v.documentType,publicationDate:v.publicationDate||null,dataPeriodStart:v.dataPeriodStart||null,dataPeriodEnd:null,language:'zh-CN',status:'DRAFT',originalUrl:'',localFileId:null,version:1,supersedesDocumentId:null,supersededByDocumentId:null,relatedIndicatorIds:v.indicators.split(',').map(x=>x.trim()).filter(Boolean),relatedEvidenceIds:[],relatedDataRecordIds:[],relatedResearchIds:[],methodologyIds:[],tags:[],quality:{completeness:null,machineReadable:null,methodologyClarity:null,citationQuality:null},createdAt:window.MinshengResearchMemory.today(),updatedAt:window.MinshengResearchMemory.today(),notes:'本地资料登记；附件仅保存元数据。',deleted:false};if(file){const metadata={id:`file_${Date.now()}`,fileName:file.name,fileType:(file.name.split('.').pop()||'').toLowerCase(),mimeType:file.type||null,size:file.size,importedAt:new Date().toISOString(),checksum:null,storageType:'metadata_only',status:'ACTIVE',sourceDocumentId:id,notes:''};const err=window.MinshengFileRegistry.validate(metadata),dup=window.MinshengFileRegistry.duplicate(data.files,metadata);if(err||dup){alert(err||'存在相同文件元数据，未登记。');return}data.files.push(metadata);doc.localFileId=metadata.id;}data.sourceDocuments.push(doc);audit('CREATE_DOCUMENT','source_document',id,null,doc,'Manual document intake');saveLocalResearch();renderLibrary();renderSources();byId('modal').classList.remove('show');};}
function openDocumentDetail(id){const d=data.sourceDocuments.find(x=>x.id===id),file=data.files.find(f=>f.id===d?.localFileId),records=data.records.filter(r=>r.sourceDocumentId===id),evidence=data.evidence.filter(e=>e.sourceDocumentId===id),methods=data.methodologies.filter(m=>m.sourceDocumentIds?.includes(id)),versions=data.sourceDocuments.filter(x=>x.id===id||x.supersedesDocumentId===id||x.supersededByDocumentId===id);if(!d)return;openDialog(`<p class="eyebrow">Source Document Detail</p><h2>${d.title}</h2><p><span class="metric-chip ${d.status==='ACTIVE'?'green':'neutral'}">${d.status}</span> <span class="demo-flag">${d.status==='MOCK'?'MOCK':'LOCAL METADATA'}</span></p><div class="detail-grid"><div><b>机构 / 类型</b><span>${sourceOf(d.sourceId).name} / ${d.documentType}</span></div><div><b>发布日期</b><span>${fmtDate(d.publicationDate)}</span></div><div><b>数据覆盖期</b><span>${d.dataPeriodStart||'未登记'} — ${d.dataPeriodEnd||'未登记'}</span></div><div><b>版本</b><span>v${d.version}</span></div><div><b>本地附件</b><span>${file?file.fileName+'（metadata_only）':'未登记'}</span></div><div><b>原始 URL</b><span>${d.originalUrl||'未登记'}</span></div></div><h3>关联指标</h3><p class="detail-copy">${d.relatedIndicatorIds.map(x=>indicatorOf(x)?.name||x).join('；')||'未登记'}</p><h3>此文件产生的数据</h3><div class="source-records">${records.map(r=>`<button data-record-open="${r.id}">${r.indicatorId} · ${r.period} · ${r.convertedValue??'数据不足'} ${r.convertedUnit||r.unit}</button>`).join('')||'<p>未登记 Data Record</p>'}</div><h3>关联研究证据</h3><div class="source-records">${evidence.map(e=>`<button data-evidence-open="${e.id}">${e.title}</button>`).join('')||'<p>未登记 Evidence</p>'}</div><h3>统计口径</h3><p class="detail-copy">${methods.map(m=>m.title).join('；')||'未登记'}</p><h3>文件版本历史</h3><p class="detail-copy">${versions.map(v=>`${v.id} · v${v.version} · ${v.status}`).join('<br>')}</p><div class="modal-actions">${d.deleted?'<button class="secondary" id="restoreDocument">恢复资料</button>':'<button class="secondary danger" id="archiveDocument">归档/删除资料</button>'}<button class="primary close">关闭</button></div>`);const modal=byId('modal');modal.querySelectorAll('[data-record-open]').forEach(b=>b.onclick=()=>openRecordDetail(b.dataset.recordOpen));modal.querySelectorAll('[data-evidence-open]').forEach(b=>b.onclick=()=>openEvidenceDetail(b.dataset.evidenceOpen));modal.querySelector('.close').onclick=()=>modal.classList.remove('show');if(byId('archiveDocument'))byId('archiveDocument').onclick=()=>{const reason=prompt('请输入归档/删除原因：');if(!reason)return;window.MinshengSoftDelete.mark(d,reason);d.status='DELETED';audit('ARCHIVE_DOCUMENT','source_document',d.id,null,d,reason);saveLocalResearch();renderLibrary();byId('modal').classList.remove('show');};if(byId('restoreDocument'))byId('restoreDocument').onclick=()=>{window.MinshengSoftDelete.restore(d);d.status='ARCHIVED';audit('UPDATE_DOCUMENT','source_document',d.id,null,d,'Restore document');saveLocalResearch();renderLibrary();openDocumentDetail(d.id);};}
function renderMethodologies(){const section=byId('methodologies');if(!section)return;section.innerHTML=`<div class="view-intro"><p class="eyebrow">Methodology Intelligence</p><h1>统计口径</h1><p>口径变化不等于数值错误；可比性为 BREAK 时，前后数据不能默认连成连续序列。</p></div><div class="method-grid">${data.indicators.map(i=>{const methods=data.methodologies.filter(m=>m.indicatorIds.includes(i.id)),events=data.methodologyEvents.filter(e=>e.indicatorId===i.id);if(!methods.length)return '';return `<button class="panel method-card" data-method-indicator="${i.id}"><p class="eyebrow">${i.name}</p><h2>${methods.find(m=>m.status==='ACTIVE')?.title||'未登记当前口径'}</h2><p>${events.some(e=>e.comparabilityImpact==='BREAK')?'<span class="break-badge">统计口径发生变化 · BREAK</span>':'<span class="metric-chip green">可比性无已知断点</span>'}</p><small>历史版本 ${methods.length} · 变更事件 ${events.length}</small></button>`}).join('')||'<p>暂无统计口径登记。</p>'}</div>`;section.querySelectorAll('[data-method-indicator]').forEach(b=>b.onclick=()=>openMethodologyDetail(b.dataset.methodIndicator));}
function openMethodologyDetail(indicatorId){const indicator=indicatorOf(indicatorId),methods=data.methodologies.filter(m=>m.indicatorIds.includes(indicatorId)).sort((a,b)=>(a.validFrom||'').localeCompare(b.validFrom||'')),events=data.methodologyEvents.filter(e=>e.indicatorId===indicatorId);openDialog(`<p class="eyebrow">Methodology Timeline</p><h2>${indicator?.name||indicatorId}</h2>${events.some(e=>e.comparabilityImpact==='BREAK')?'<div class="method-warning">统计口径发生变化：前后数据可能不可直接比较。</div>':''}<div class="method-timeline">${methods.map(m=>`<div><b>${m.validFrom||'未登记'} — ${m.validTo||'至今'}</b><span>${m.title} · ${m.status}</span><small>${m.comparabilityImpact} · ${m.definition}</small></div>`).join('')}</div><h3>口径变更事件</h3>${events.map(e=>`<div class="method-event"><b>${e.effectivePeriod} · ${e.changeType}</b><span>${e.comparabilityImpact} / ${e.severity}</span><p>${e.description}</p><small>来源文件：${e.sourceDocumentId||'未登记'}</small></div>`).join('')||'<p>未登记变更事件。</p>'}`);}
function augmentIntakeV05(){const actions=document.querySelector('.intake-actions');if(!actions||actions.querySelector('#registerDocumentFromIntake'))return;actions.insertAdjacentHTML('beforeend','<button class="secondary" id="registerDocumentFromIntake">登记资料文件</button>');byId('registerDocumentFromIntake').onclick=openDocumentForm;}
var renderDataIntakeV04=renderDataIntake;renderDataIntake=function(){renderDataIntakeV04();augmentIntakeV05();};
function genericCsv(text){return window.MinshengCsv.parse(text);}
var openRecordDetailV04=openRecordDetail;openRecordDetail=function(id){openRecordDetailV04(id);const r=data.records.find(x=>x.id===id);if(!r)return;const modal=byId('modal'),box=modal.querySelector('.modal');box.insertAdjacentHTML('beforeend',`<div class="modal-actions">${r.deleted?'<button class="secondary" id="restoreRecord">恢复记录</button>':'<button class="secondary danger" id="deleteRecord">删除记录</button>'}</div>`);if(byId('deleteRecord'))byId('deleteRecord').onclick=()=>{const reason=prompt('请输入删除原因（例如：重复导入、来源错误、数据无效）：');if(!reason)return;window.MinshengSoftDelete.mark(r,reason);audit('DELETE','data_record',r.id,null,r,reason);saveLocalResearch();hydrateIndicatorsFromRecords();renderDataIntake();renderDataHealth();byId('modal').classList.remove('show');};if(byId('restoreRecord'))byId('restoreRecord').onclick=()=>{window.MinshengSoftDelete.restore(r);audit('RESTORE_RECORD','data_record',r.id,null,r,'Restore record');saveLocalResearch();hydrateIndicatorsFromRecords();renderDataIntake();renderDataHealth();openRecordDetail(r.id);};};
var openEvidenceDetailV04=openEvidenceDetail;openEvidenceDetail=function(id){openEvidenceDetailV04(id);const e=data.evidence.find(x=>x.id===id),doc=data.sourceDocuments.find(d=>d.id===e?.sourceDocumentId);if(!e)return;byId('modal').querySelector('.modal').insertAdjacentHTML('beforeend',`<div class="document-locator"><b>来源文件与内部定位</b><p>${doc?doc.title:'来源文件未登记'}</p><span>${e.locator?.page?`第 ${e.locator.page} 页`:'暂无文档内部定位'}${e.locator?.table?' · '+e.locator.table:''}${e.locator?.row?' · '+e.locator.row:''}</span></div>`);};
var openResearchDetailV04=openResearchDetail;openResearchDetail=function(id){openResearchDetailV04(id);const r=data.research.find(x=>x.id===id),support=data.evidence.filter(e=>e.relatedResearch.includes(id)&&e.stance==='SUPPORT'),byType={};support.forEach(e=>byType[e.sourceType]=(byType[e.sourceType]||0)+1);const max=Math.max(0,...Object.values(byType)),warning=support.length&&max/support.length>=.8;byId('modal').querySelector('.modal').insertAdjacentHTML('beforeend',`<div class="source-density"><b>支持证据来源构成</b><p>${Object.entries(byType).map(([t,n])=>`${t}：${n}`).join(' · ')||'暂无支持证据'}</p>${warning?'<span class="break-badge">来源集中度较高 · DEMO 阈值 80%</span>':''}</div>`);};
var renderSourcesV04=renderSources;renderSources=function(){renderSourcesV04();const section=byId('sources');section?.querySelectorAll('[data-source]').forEach(button=>{const id=button.dataset.source,docs=data.sourceDocuments.filter(d=>d.sourceId===id&&!d.deleted).length,evidence=data.evidence.filter(e=>e.sourceId===id).length,methods=data.methodologies.filter(m=>m.sourceId===id).length;button.insertAdjacentHTML('beforeend',`<small class="source-coverage">资料 ${docs} · Evidence ${evidence} · 口径 ${methods}</small>`);});};
function exportSnapshot(){window.MinshengImportExport.download('minsheng-os-v05-snapshot.json',{version:'0.5',exportedAt:new Date().toISOString(),sources:data.sources,sourceDocuments:data.sourceDocuments,files:data.files,methodologies:data.methodologies,methodologyEvents:data.methodologyEvents,dataRecords:data.records,evidence:data.evidence,research:data.research,auditLog:data.auditLog,localState:{inbox:data.inbox,batches:data.batches,canonicalOverrides:data.canonicalOverrides}});}
function resetDemo(){if(!confirm('将清除本地研究、数据与资料登记修改，并恢复 DEMO / MOCK 数据，是否继续？'))return;window.MinshengPersistence.clear();['research','evidence','inbox','indicators','records','rawPayloads','batches','auditLog','canonicalOverrides','sourceDocuments','files','methodologies','methodologyEvents','documentSections','documentTables'].forEach(key=>data[key]=window.MinshengPersistence.clone(baseData[key]));v05Migrate();hydrateIndicatorsFromRecords();renderEvidenceEngine();renderResearchWorkspace();renderResearchNotes();renderDataHealth();renderDataIntake();renderSources();renderLibrary();renderMethodologies();renderIndicators();}
function importJsonFile(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const parsed=window.MinshengImportExport.parseJson(reader.result);if(parsed.errors.length){alert(parsed.errors.join('\n'));return}const incoming=parsed.value,map=[['evidence','evidence'],['research','research'],['indicators','indicators'],['dataRecords','records'],['records','records'],['sourceDocuments','sourceDocuments'],['files','files'],['methodologies','methodologies'],['methodologyEvents','methodologyEvents'],['auditLog','auditLog']];const errors=[],seen={};map.forEach(([input,target])=>(incoming[input]||[]).forEach(item=>{seen[target]??=new Set(data[target].map(x=>x.id));if(!item?.id)errors.push(`${input}: 缺少 id`);else if(seen[target].has(item.id))errors.push(`${input}: 重复 id ${item.id}`);else seen[target].add(item.id);}));if(errors.length){alert('导入失败：\n'+errors.join('\n'));return}map.forEach(([input,target])=>{if(Array.isArray(incoming[input]))data[target].push(...incoming[input])});v05Migrate();saveLocalResearch();hydrateIndicatorsFromRecords();renderEvidenceEngine();renderResearchWorkspace();renderDataIntake();renderSources();renderLibrary();renderMethodologies();alert(`JSON 快照导入完成${incoming.version&&incoming.version!=='0.5'?'（已按兼容字段迁移）':''}。`);};reader.readAsText(file);}
function init() {
  /* v0.29 keeps the established data initialization but defers all legacy DOM renderers to the Cockpit route layer. */
  if(document.getElementById('researchCockpitRoot')){v05Migrate();hydrateIndicatorsFromRecords();return;}
  document.querySelector('header').insertAdjacentHTML('afterend','<div class="global-demo-notice"><b>DEMO / MOCK 数据工作区</b><span>当前指标、城市评分、情报与情景均为模拟研究数据；不可作为实时经济事实或决策依据。</span></div>');
  createV03Views(); createV04Views(); createV05Views(); v05Migrate(); hydrateIndicatorsFromRecords(); renderIndicators(); renderResearchNotes(); renderDataHealth(); renderDashboardFeed(); renderIntelligenceFeed(); renderCausalGraph(); renderCityResearch(); renderModules(); renderScenario(); renderEvidenceEngine(); renderResearchWorkspace(); renderDataIntake(); renderSources(); renderLibrary(); renderMethodologies(); bindStaticEvents();
  byId('newResearch').onclick=openCreateResearch;
}
init();
function renderBankExposureDisclosure(){const map=document.querySelector('.system-map');if(!map||document.querySelector('.bank-exposure-disclosure'))return;const records=data.bankDisclosureRecords||[],mortgages=records.filter(r=>r.exposureConcept==='PERSONAL_MORTGAGE_LOANS').length,property=records.filter(r=>r.exposureConcept==='CORPORATE_REAL_ESTATE_LOANS').length,lgfv=data.bankDisclosureAssessments?.find(x=>x.id==='bank_lgfv_direct_exposure_2025');map.insertAdjacentHTML('afterend',`<section class="panel bank-exposure-disclosure"><div class="panel-title"><div><p class="eyebrow">v0.21 · AUDITED ENTITY DISCLOSURE</p><h2>银行房地产敞口证据包</h2></div><span class="metric-chip neutral">银行样本披露，不代表全国银行业</span></div><p class="detail-copy"><b>贷款敞口不等于损失；不良率不等于违约概率。</b> 六条已核验记录仅用于银行样本描述，不进入全国 records、DSTI、房企现金桥或损失计算。</p><div class="health-grid"><span>按揭记录 <b>${mortgages}</b></span><span>房地产业贷款 <b>${property}</b></span><span>已视觉核验 <b>${records.filter(r=>r.visualReviewStatus==='VISUALLY_VERIFIED_BY_CODEX').length}</b></span><span>LGFV 直接敞口 <b>${lgfv?.value??'UNKNOWN'}</b></span></div></section>`);}
renderBankExposureDisclosure();
function renderBankAssetQualityDisclosure(){const target=document.querySelector('.bank-exposure-disclosure');if(!target||document.querySelector('.bank-asset-quality-disclosure'))return;const records=data.bankAssetQualityRecords||[],derived=data.bankAssetQualityDerivedRecords||[],current=records.filter(x=>x.reportingPeriod==='2025-12-31'),scopeRows=['CORPORATE_REAL_ESTATE','PERSONAL_MORTGAGE'].map(portfolio=>({portfolio,label:portfolio==='CORPORATE_REAL_ESTATE'?'房地产业公司':'个人住房按揭',rows:current.filter(x=>x.portfolio===portfolio),npl:current.filter(x=>x.portfolio===portfolio&&x.concept.endsWith('_NPL_BALANCE')).reduce((n,x)=>n+x.value,0)}));const fmt=n=>new Intl.NumberFormat('zh-CN').format(n);target.insertAdjacentHTML('afterend',`<section class="panel bank-asset-quality-disclosure"><div class="panel-title"><div><p class="eyebrow">v0.22 · AUDITED ENTITY DISCLOSURE</p><h2>银行房地产资产质量证据包</h2></div><span class="metric-chip amber">样本观察，非全国估计</span></div><p class="detail-copy"><b>银行样本披露，不代表全国银行业。</b> 不良率是会计分类结果，不是压力情景中的违约概率；不良余额和拨备均不等于最终经济损失。</p><div class="health-grid"><span>银行 <b>3</b></span><span>已发布记录 <b>${records.length}</b></span><span>安全派生 <b>${derived.filter(x=>x.reconciliationStatus==='ROUNDING_MATCH').length}</b></span><span>拒绝 / 不匹配 <b>${(data.bankAssetQualityAssessments||[]).filter(x=>x.status!=='UNKNOWN').length}</b></span></div><table class="asset-quality-table"><thead><tr><th>范围</th><th>2025 披露</th><th>不良余额</th><th>审计边界</th></tr></thead><tbody>${scopeRows.map(x=>`<tr><td><b>${x.label}</b><small>ICBC / ABC / PSBC</small></td><td>${x.rows.filter(r=>r.concept.endsWith('_NPL_RATIO')).map(r=>`${r.entity} ${r.value.toFixed(2)}%`).join(' · ')}</td><td>${fmt(x.npl)} RMB million</td><td><span class="metric-chip neutral">BANK SAMPLE ONLY</span></td></tr>`).join('')}</tbody></table><p class="evidence-note">仅保留经审计实体披露及同口径可复核派生；不进入 PD/LGD/EAD、损失计算、LGFV 估计或全国银行业汇总。</p></section>`);}
renderBankAssetQualityDisclosure();
